/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum AbstractNodeType {
  ANT_UNKNOWN,
  ANT_ATOM,
  ANT_OBJECT,
  ANT_PROPERTY,
  ANT_IMPORT,
  ANT_VARIABLE_SET,
  ANT_VARIABLE_ACCESS;

  public final int swigValue() {
    return swigValue;
  }

  public static AbstractNodeType swigToEnum(int swigValue) {
    AbstractNodeType[] swigValues = AbstractNodeType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AbstractNodeType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AbstractNodeType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AbstractNodeType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AbstractNodeType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AbstractNodeType(AbstractNodeType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

