/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class Affine3 extends TransformBaseReal {
  private transient long swigCPtr;

  protected Affine3(long cPtr, boolean cMemoryOwn) {
    super(OgreJNI.Affine3_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Affine3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_Affine3(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Affine3() {
    this(OgreJNI.new_Affine3__SWIG_0(), true);
  }

  public Affine3(Vector3 position, Quaternion orientation, Vector3 scale) {
    this(OgreJNI.new_Affine3__SWIG_1(Vector3.getCPtr(position), position, Quaternion.getCPtr(orientation), orientation, Vector3.getCPtr(scale), scale), true);
  }

  public Affine3(Vector3 position, Quaternion orientation) {
    this(OgreJNI.new_Affine3__SWIG_2(Vector3.getCPtr(position), position, Quaternion.getCPtr(orientation), orientation), true);
  }

  public Affine3(SWIGTYPE_p_float arr) {
    this(OgreJNI.new_Affine3__SWIG_4(SWIGTYPE_p_float.getCPtr(arr)), true);
  }

  public Affine3(float m00, float m01, float m02, float m03, float m10, float m11, float m12, float m13, float m20, float m21, float m22, float m23) {
    this(OgreJNI.new_Affine3__SWIG_5(m00, m01, m02, m03, m10, m11, m12, m13, m20, m21, m22, m23), true);
  }

  public Affine3(Matrix4 mat) {
    this(OgreJNI.new_Affine3__SWIG_6(Matrix4.getCPtr(mat), mat), true);
  }

  public Affine3 inverse() {
    return new Affine3(OgreJNI.Affine3_inverse(swigCPtr, this), true);
  }

  public void decomposition(Vector3 position, Vector3 scale, Quaternion orientation) {
    OgreJNI.Affine3_decomposition(swigCPtr, this, Vector3.getCPtr(position), position, Vector3.getCPtr(scale), scale, Quaternion.getCPtr(orientation), orientation);
  }

  public static Affine3 getTrans(Vector3 v) {
    return new Affine3(OgreJNI.Affine3_getTrans__SWIG_1(Vector3.getCPtr(v), v), true);
  }

  public static Affine3 getTrans(float t_x, float t_y, float t_z) {
    return new Affine3(OgreJNI.Affine3_getTrans__SWIG_2(t_x, t_y, t_z), true);
  }

  public static Affine3 getScale(Vector3 v) {
    return new Affine3(OgreJNI.Affine3_getScale__SWIG_0(Vector3.getCPtr(v), v), true);
  }

  public static Affine3 getScale(float s_x, float s_y, float s_z) {
    return new Affine3(OgreJNI.Affine3_getScale__SWIG_1(s_x, s_y, s_z), true);
  }

  public static Affine3 getZERO() {
    long cPtr = OgreJNI.Affine3_ZERO_get();
    return (cPtr == 0) ? null : new Affine3(cPtr, false);
  }

  public static Affine3 getIDENTITY() {
    long cPtr = OgreJNI.Affine3_IDENTITY_get();
    return (cPtr == 0) ? null : new Affine3(cPtr, false);
  }

  public String toString() {
    return OgreJNI.Affine3_toString(swigCPtr, this);
  }

  public Vector4 __mul__(Vector4 v) {
    return new Vector4(OgreJNI.Affine3___mul____SWIG_0(swigCPtr, this, Vector4.getCPtr(v), v), true);
  }

  public Vector3 __mul__(Vector3 v) {
    return new Vector3(OgreJNI.Affine3___mul____SWIG_1(swigCPtr, this, Vector3.getCPtr(v), v), true);
  }

  public Affine3 __mul__(Affine3 m) {
    return new Affine3(OgreJNI.Affine3___mul____SWIG_2(swigCPtr, this, Affine3.getCPtr(m), m), true);
  }

}
