/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class AnimationStateMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AnimationStateMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AnimationStateMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_AnimationStateMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AnimationStateMap() {
    this(OgreJNI.new_AnimationStateMap__SWIG_0(), true);
  }

  public AnimationStateMap(AnimationStateMap arg0) {
    this(OgreJNI.new_AnimationStateMap__SWIG_1(AnimationStateMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return OgreJNI.AnimationStateMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return OgreJNI.AnimationStateMap_empty(swigCPtr, this);
  }

  public void clear() {
    OgreJNI.AnimationStateMap_clear(swigCPtr, this);
  }

  public AnimationState get(String key) {
    long cPtr = OgreJNI.AnimationStateMap_get(swigCPtr, this, key);
    return (cPtr == 0) ? null : new AnimationState(cPtr, false);
  }

  public void set(String key, AnimationState x) {
    OgreJNI.AnimationStateMap_set(swigCPtr, this, key, AnimationState.getCPtr(x), x);
  }

  public void del(String key) {
    OgreJNI.AnimationStateMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return OgreJNI.AnimationStateMap_has_key(swigCPtr, this, key);
  }

}
