/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class AnimationStateControllerValue {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AnimationStateControllerValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AnimationStateControllerValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_AnimationStateControllerValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AnimationStateControllerValue(AnimationState targetAnimationState, boolean addTime) {
    this(OgreJNI.new_AnimationStateControllerValue__SWIG_0(AnimationState.getCPtr(targetAnimationState), targetAnimationState, addTime), true);
  }

  public AnimationStateControllerValue(AnimationState targetAnimationState) {
    this(OgreJNI.new_AnimationStateControllerValue__SWIG_1(AnimationState.getCPtr(targetAnimationState), targetAnimationState), true);
  }

  public static ControllerValueRealPtr create(AnimationState targetAnimationState, boolean addTime) {
    return new ControllerValueRealPtr(OgreJNI.AnimationStateControllerValue_create__SWIG_0(AnimationState.getCPtr(targetAnimationState), targetAnimationState, addTime), true);
  }

  public static ControllerValueRealPtr create(AnimationState targetAnimationState) {
    return new ControllerValueRealPtr(OgreJNI.AnimationStateControllerValue_create__SWIG_1(AnimationState.getCPtr(targetAnimationState), targetAnimationState), true);
  }

  public float getValue() {
    return OgreJNI.AnimationStateControllerValue_getValue(swigCPtr, this);
  }

  public void setValue(float value) {
    OgreJNI.AnimationStateControllerValue_setValue(swigCPtr, this, value);
  }

}
