/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class APKZipArchiveFactory extends EmbeddedZipArchiveFactory {
  private transient long swigCPtr;

  protected APKZipArchiveFactory(long cPtr, boolean cMemoryOwn) {
    super(OgreJNI.APKZipArchiveFactory_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(APKZipArchiveFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_APKZipArchiveFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public APKZipArchiveFactory(SWIGTYPE_p_AAssetManager assetMgr) {
    this(OgreJNI.new_APKZipArchiveFactory(SWIGTYPE_p_AAssetManager.getCPtr(assetMgr)), true);
  }

  public Archive createInstance(String name, boolean readOnly) {
    long cPtr = OgreJNI.APKZipArchiveFactory_createInstance(swigCPtr, this, name, readOnly);
    return (cPtr == 0) ? null : new Archive(cPtr, false);
  }

  public void destroyInstance(Archive ptr) {
    OgreJNI.APKZipArchiveFactory_destroyInstance(swigCPtr, this, Archive.getCPtr(ptr), ptr);
  }

}
