/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public interface BitesConstants {
  public final static int SDLK_DELETE = BitesJNI.SDLK_DELETE_get();
  public final static int SDLK_RETURN = BitesJNI.SDLK_RETURN_get();
  public final static int SDLK_ESCAPE = BitesJNI.SDLK_ESCAPE_get();
  public final static int SDLK_SPACE = BitesJNI.SDLK_SPACE_get();
  public final static int SDLK_F1 = BitesJNI.SDLK_F1_get();
  public final static int SDLK_F2 = BitesJNI.SDLK_F2_get();
  public final static int SDLK_F3 = BitesJNI.SDLK_F3_get();
  public final static int SDLK_F4 = BitesJNI.SDLK_F4_get();
  public final static int SDLK_F5 = BitesJNI.SDLK_F5_get();
  public final static int SDLK_F6 = BitesJNI.SDLK_F6_get();
  public final static int SDLK_F7 = BitesJNI.SDLK_F7_get();
  public final static int SDLK_F8 = BitesJNI.SDLK_F8_get();
  public final static int SDLK_F9 = BitesJNI.SDLK_F9_get();
  public final static int SDLK_F10 = BitesJNI.SDLK_F10_get();
  public final static int SDLK_F11 = BitesJNI.SDLK_F11_get();
  public final static int SDLK_F12 = BitesJNI.SDLK_F12_get();
  public final static int SDLK_PRINTSCREEN = BitesJNI.SDLK_PRINTSCREEN_get();
  public final static int SDLK_SCROLLLOCK = BitesJNI.SDLK_SCROLLLOCK_get();
  public final static int SDLK_PAUSE = BitesJNI.SDLK_PAUSE_get();
  public final static int SDLK_INSERT = BitesJNI.SDLK_INSERT_get();
  public final static int SDLK_HOME = BitesJNI.SDLK_HOME_get();
  public final static int SDLK_PAGEUP = BitesJNI.SDLK_PAGEUP_get();
  public final static int SDLK_END = BitesJNI.SDLK_END_get();
  public final static int SDLK_PAGEDOWN = BitesJNI.SDLK_PAGEDOWN_get();
  public final static int SDLK_RIGHT = BitesJNI.SDLK_RIGHT_get();
  public final static int SDLK_LEFT = BitesJNI.SDLK_LEFT_get();
  public final static int SDLK_DOWN = BitesJNI.SDLK_DOWN_get();
  public final static int SDLK_UP = BitesJNI.SDLK_UP_get();
  public final static int SDLK_NUMLOCKCLEAR = BitesJNI.SDLK_NUMLOCKCLEAR_get();
  public final static int SDLK_KP_DIVIDE = BitesJNI.SDLK_KP_DIVIDE_get();
  public final static int SDLK_KP_MULTIPLY = BitesJNI.SDLK_KP_MULTIPLY_get();
  public final static int SDLK_KP_MINUS = BitesJNI.SDLK_KP_MINUS_get();
  public final static int SDLK_KP_PLUS = BitesJNI.SDLK_KP_PLUS_get();
  public final static int SDLK_KP_ENTER = BitesJNI.SDLK_KP_ENTER_get();
  public final static int SDLK_KP_1 = BitesJNI.SDLK_KP_1_get();
  public final static int SDLK_KP_2 = BitesJNI.SDLK_KP_2_get();
  public final static int SDLK_KP_3 = BitesJNI.SDLK_KP_3_get();
  public final static int SDLK_KP_4 = BitesJNI.SDLK_KP_4_get();
  public final static int SDLK_KP_5 = BitesJNI.SDLK_KP_5_get();
  public final static int SDLK_KP_6 = BitesJNI.SDLK_KP_6_get();
  public final static int SDLK_KP_7 = BitesJNI.SDLK_KP_7_get();
  public final static int SDLK_KP_8 = BitesJNI.SDLK_KP_8_get();
  public final static int SDLK_KP_9 = BitesJNI.SDLK_KP_9_get();
  public final static int SDLK_KP_0 = BitesJNI.SDLK_KP_0_get();
  public final static int SDLK_KP_PERIOD = BitesJNI.SDLK_KP_PERIOD_get();
  public final static int SDLK_LSHIFT = BitesJNI.SDLK_LSHIFT_get();
  public final static int KMOD_ALT = BitesJNI.KMOD_ALT_get();
  public final static int KMOD_CTRL = BitesJNI.KMOD_CTRL_get();
  public final static int KMOD_GUI = BitesJNI.KMOD_GUI_get();
  public final static int KMOD_SHIFT = BitesJNI.KMOD_SHIFT_get();
  public final static int KMOD_NUM = BitesJNI.KMOD_NUM_get();

  public final static int OGRE_BITES_HAVE_SDL = BitesJNI.OGRE_BITES_HAVE_SDL_get();
}
