/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class BoneList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BoneList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BoneList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_BoneList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BoneList() {
    this(OgreJNI.new_BoneList__SWIG_0(), true);
  }

  public BoneList(long n) {
    this(OgreJNI.new_BoneList__SWIG_1(n), true);
  }

  public long size() {
    return OgreJNI.BoneList_size(swigCPtr, this);
  }

  public long capacity() {
    return OgreJNI.BoneList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    OgreJNI.BoneList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return OgreJNI.BoneList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    OgreJNI.BoneList_clear(swigCPtr, this);
  }

  public void add(Bone x) {
    OgreJNI.BoneList_add(swigCPtr, this, Bone.getCPtr(x), x);
  }

  public Bone get(int i) {
    long cPtr = OgreJNI.BoneList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public void set(int i, Bone val) {
    OgreJNI.BoneList_set(swigCPtr, this, i, Bone.getCPtr(val), val);
  }

}
