/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum CapabilitiesCategory {
  CAPS_CATEGORY_COMMON(OgreJNI.CAPS_CATEGORY_COMMON_get()),
  CAPS_CATEGORY_COMMON_2(OgreJNI.CAPS_CATEGORY_COMMON_2_get()),
  CAPS_CATEGORY_D3D9(OgreJNI.CAPS_CATEGORY_D3D9_get()),
  CAPS_CATEGORY_GL(OgreJNI.CAPS_CATEGORY_GL_get()),
  CAPS_CATEGORY_COMMON_3(OgreJNI.CAPS_CATEGORY_COMMON_3_get()),
  CAPS_CATEGORY_COUNT(OgreJNI.CAPS_CATEGORY_COUNT_get());

  public final int swigValue() {
    return swigValue;
  }

  public static CapabilitiesCategory swigToEnum(int swigValue) {
    CapabilitiesCategory[] swigValues = CapabilitiesCategory.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CapabilitiesCategory swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CapabilitiesCategory.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CapabilitiesCategory() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CapabilitiesCategory(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CapabilitiesCategory(CapabilitiesCategory swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

