/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class ControllerFunctionPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ControllerFunctionPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ControllerFunctionPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_ControllerFunctionPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ControllerFunctionPtr(SWIGTYPE_p_std__nullptr_t arg0) {
    this(OgreJNI.new_ControllerFunctionPtr__SWIG_0(SWIGTYPE_p_std__nullptr_t.getCPtr(arg0)), true);
  }

  public ControllerFunctionPtr() {
    this(OgreJNI.new_ControllerFunctionPtr__SWIG_1(), true);
  }

  public ControllerFunctionPtr(ControllerFunctionPtr r) {
    this(OgreJNI.new_ControllerFunctionPtr__SWIG_2(ControllerFunctionPtr.getCPtr(r), r), true);
  }

  public SWIGTYPE_p_Ogre__ControllerFunctionT_float_t __deref__() {
    long cPtr = OgreJNI.ControllerFunctionPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__ControllerFunctionT_float_t(cPtr, false);
  }

}
