/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class DataStream {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DataStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_DataStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getName() {
    return OgreJNI.DataStream_getName(swigCPtr, this);
  }

  public int getAccessMode() {
    return OgreJNI.DataStream_getAccessMode(swigCPtr, this);
  }

  public boolean isReadable() {
    return OgreJNI.DataStream_isReadable(swigCPtr, this);
  }

  public boolean isWriteable() {
    return OgreJNI.DataStream_isWriteable(swigCPtr, this);
  }

  public long read(SWIGTYPE_p_void buf, long count) {
    return OgreJNI.DataStream_read(swigCPtr, this, SWIGTYPE_p_void.getCPtr(buf), count);
  }

  public long write(SWIGTYPE_p_void buf, long count) {
    return OgreJNI.DataStream_write(swigCPtr, this, SWIGTYPE_p_void.getCPtr(buf), count);
  }

  public long readLine(String buf, long maxCount, String delim) {
    return OgreJNI.DataStream_readLine__SWIG_0(swigCPtr, this, buf, maxCount, delim);
  }

  public long readLine(String buf, long maxCount) {
    return OgreJNI.DataStream_readLine__SWIG_1(swigCPtr, this, buf, maxCount);
  }

  public String getLine(boolean trimAfter) {
    return OgreJNI.DataStream_getLine__SWIG_0(swigCPtr, this, trimAfter);
  }

  public String getLine() {
    return OgreJNI.DataStream_getLine__SWIG_1(swigCPtr, this);
  }

  public String getAsString() {
    return OgreJNI.DataStream_getAsString(swigCPtr, this);
  }

  public long skipLine(String delim) {
    return OgreJNI.DataStream_skipLine__SWIG_0(swigCPtr, this, delim);
  }

  public long skipLine() {
    return OgreJNI.DataStream_skipLine__SWIG_1(swigCPtr, this);
  }

  public void skip(int count) {
    OgreJNI.DataStream_skip(swigCPtr, this, count);
  }

  public void seek(long pos) {
    OgreJNI.DataStream_seek(swigCPtr, this, pos);
  }

  public long tell() {
    return OgreJNI.DataStream_tell(swigCPtr, this);
  }

  public boolean eof() {
    return OgreJNI.DataStream_eof(swigCPtr, this);
  }

  public long size() {
    return OgreJNI.DataStream_size(swigCPtr, this);
  }

  public void close() {
    OgreJNI.DataStream_close(swigCPtr, this);
  }

  public enum AccessMode {
    READ(OgreJNI.DataStream_READ_get()),
    WRITE(OgreJNI.DataStream_WRITE_get());

    public final int swigValue() {
      return swigValue;
    }

    public static AccessMode swigToEnum(int swigValue) {
      AccessMode[] swigValues = AccessMode.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (AccessMode swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + AccessMode.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private AccessMode() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private AccessMode(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private AccessMode(AccessMode swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

}
