/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class DataStreamPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DataStreamPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataStreamPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_DataStreamPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DataStreamPtr(SWIGTYPE_p_std__nullptr_t arg0) {
    this(OgreJNI.new_DataStreamPtr__SWIG_0(SWIGTYPE_p_std__nullptr_t.getCPtr(arg0)), true);
  }

  public DataStreamPtr() {
    this(OgreJNI.new_DataStreamPtr__SWIG_1(), true);
  }

  public DataStreamPtr(DataStreamPtr r) {
    this(OgreJNI.new_DataStreamPtr__SWIG_2(DataStreamPtr.getCPtr(r), r), true);
  }

  public DataStream __deref__() {
    long cPtr = OgreJNI.DataStreamPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new DataStream(cPtr, false);
  }

  public String getName() {
    return OgreJNI.DataStreamPtr_getName(swigCPtr, this);
  }

  public int getAccessMode() {
    return OgreJNI.DataStreamPtr_getAccessMode(swigCPtr, this);
  }

  public boolean isReadable() {
    return OgreJNI.DataStreamPtr_isReadable(swigCPtr, this);
  }

  public boolean isWriteable() {
    return OgreJNI.DataStreamPtr_isWriteable(swigCPtr, this);
  }

  public long read(SWIGTYPE_p_void buf, long count) {
    return OgreJNI.DataStreamPtr_read(swigCPtr, this, SWIGTYPE_p_void.getCPtr(buf), count);
  }

  public long write(SWIGTYPE_p_void buf, long count) {
    return OgreJNI.DataStreamPtr_write(swigCPtr, this, SWIGTYPE_p_void.getCPtr(buf), count);
  }

  public long readLine(String buf, long maxCount, String delim) {
    return OgreJNI.DataStreamPtr_readLine__SWIG_0(swigCPtr, this, buf, maxCount, delim);
  }

  public long readLine(String buf, long maxCount) {
    return OgreJNI.DataStreamPtr_readLine__SWIG_1(swigCPtr, this, buf, maxCount);
  }

  public String getLine(boolean trimAfter) {
    return OgreJNI.DataStreamPtr_getLine__SWIG_0(swigCPtr, this, trimAfter);
  }

  public String getLine() {
    return OgreJNI.DataStreamPtr_getLine__SWIG_1(swigCPtr, this);
  }

  public String getAsString() {
    return OgreJNI.DataStreamPtr_getAsString(swigCPtr, this);
  }

  public long skipLine(String delim) {
    return OgreJNI.DataStreamPtr_skipLine__SWIG_0(swigCPtr, this, delim);
  }

  public long skipLine() {
    return OgreJNI.DataStreamPtr_skipLine__SWIG_1(swigCPtr, this);
  }

  public void skip(int count) {
    OgreJNI.DataStreamPtr_skip(swigCPtr, this, count);
  }

  public void seek(long pos) {
    OgreJNI.DataStreamPtr_seek(swigCPtr, this, pos);
  }

  public long tell() {
    return OgreJNI.DataStreamPtr_tell(swigCPtr, this);
  }

  public boolean eof() {
    return OgreJNI.DataStreamPtr_eof(swigCPtr, this);
  }

  public long size() {
    return OgreJNI.DataStreamPtr_size(swigCPtr, this);
  }

  public void close() {
    OgreJNI.DataStreamPtr_close(swigCPtr, this);
  }

}
