/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class Degree {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Degree(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Degree obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_Degree(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Degree(float d) {
    this(OgreJNI.new_Degree__SWIG_0(d), true);
  }

  public Degree() {
    this(OgreJNI.new_Degree__SWIG_1(), true);
  }

  public Degree(Radian r) {
    this(OgreJNI.new_Degree__SWIG_2(Radian.getCPtr(r), r), true);
  }

  public Degree(Degree rhs) {
    this(OgreJNI.new_Degree__SWIG_3(Degree.getCPtr(rhs), rhs), true);
  }

  public float valueDegrees() {
    return OgreJNI.Degree_valueDegrees(swigCPtr, this);
  }

  public float valueRadians() {
    return OgreJNI.Degree_valueRadians(swigCPtr, this);
  }

  public float valueAngleUnits() {
    return OgreJNI.Degree_valueAngleUnits(swigCPtr, this);
  }

  public Degree __add__() {
    return new Degree(OgreJNI.Degree___add____SWIG_0(swigCPtr, this), false);
  }

  public Degree __add__(Degree d) {
    return new Degree(OgreJNI.Degree___add____SWIG_1(swigCPtr, this, Degree.getCPtr(d), d), true);
  }

  public Degree __add__(Radian r) {
    return new Degree(OgreJNI.Degree___add____SWIG_2(swigCPtr, this, Radian.getCPtr(r), r), true);
  }

  public Degree __sub__() {
    return new Degree(OgreJNI.Degree___sub____SWIG_0(swigCPtr, this), true);
  }

  public Degree __sub__(Degree d) {
    return new Degree(OgreJNI.Degree___sub____SWIG_1(swigCPtr, this, Degree.getCPtr(d), d), true);
  }

  public Degree __sub__(Radian r) {
    return new Degree(OgreJNI.Degree___sub____SWIG_2(swigCPtr, this, Radian.getCPtr(r), r), true);
  }

  public Degree __mul__(float f) {
    return new Degree(OgreJNI.Degree___mul____SWIG_0(swigCPtr, this, f), true);
  }

  public Degree __mul__(Degree f) {
    return new Degree(OgreJNI.Degree___mul____SWIG_1(swigCPtr, this, Degree.getCPtr(f), f), true);
  }

  public Degree __div__(float f) {
    return new Degree(OgreJNI.Degree___div__(swigCPtr, this, f), true);
  }

  public String toString() {
    return OgreJNI.Degree_toString(swigCPtr, this);
  }

}
