/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class Event {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Event(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Event obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BitesJNI.delete_Event(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    BitesJNI.Event_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return BitesJNI.Event_type_get(swigCPtr, this);
  }

  public void setKey(KeyboardEvent value) {
    BitesJNI.Event_key_set(swigCPtr, this, KeyboardEvent.getCPtr(value), value);
  }

  public KeyboardEvent getKey() {
    long cPtr = BitesJNI.Event_key_get(swigCPtr, this);
    return (cPtr == 0) ? null : new KeyboardEvent(cPtr, false);
  }

  public void setButton(MouseButtonEvent value) {
    BitesJNI.Event_button_set(swigCPtr, this, MouseButtonEvent.getCPtr(value), value);
  }

  public MouseButtonEvent getButton() {
    long cPtr = BitesJNI.Event_button_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MouseButtonEvent(cPtr, false);
  }

  public void setWheel(MouseWheelEvent value) {
    BitesJNI.Event_wheel_set(swigCPtr, this, MouseWheelEvent.getCPtr(value), value);
  }

  public MouseWheelEvent getWheel() {
    long cPtr = BitesJNI.Event_wheel_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MouseWheelEvent(cPtr, false);
  }

  public void setMotion(MouseMotionEvent value) {
    BitesJNI.Event_motion_set(swigCPtr, this, MouseMotionEvent.getCPtr(value), value);
  }

  public MouseMotionEvent getMotion() {
    long cPtr = BitesJNI.Event_motion_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MouseMotionEvent(cPtr, false);
  }

  public void setTfinger(TouchFingerEvent value) {
    BitesJNI.Event_tfinger_set(swigCPtr, this, TouchFingerEvent.getCPtr(value), value);
  }

  public TouchFingerEvent getTfinger() {
    long cPtr = BitesJNI.Event_tfinger_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TouchFingerEvent(cPtr, false);
  }

  public void setText(TextInputEvent value) {
    BitesJNI.Event_text_set(swigCPtr, this, TextInputEvent.getCPtr(value), value);
  }

  public TextInputEvent getText() {
    long cPtr = BitesJNI.Event_text_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TextInputEvent(cPtr, false);
  }

  public Event() {
    this(BitesJNI.new_Event(), true);
  }

}
