/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class FFPLighting extends SubRenderState {
  private transient long swigCPtr;

  protected FFPLighting(long cPtr, boolean cMemoryOwn) {
    super(RTShaderJNI.FFPLighting_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FFPLighting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTShaderJNI.delete_FFPLighting(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FFPLighting() {
    this(RTShaderJNI.new_FFPLighting(), true);
  }

  public int getExecutionOrder() {
    return RTShaderJNI.FFPLighting_getExecutionOrder(swigCPtr, this);
  }

  public void updateGpuProgramsParams(Renderable rend, Pass pass, SWIGTYPE_p_Ogre__AutoParamDataSource source, SWIGTYPE_p_Ogre__HashedVectorT_Ogre__Light_p_t pLightList) {
    RTShaderJNI.FFPLighting_updateGpuProgramsParams(swigCPtr, this, Renderable.getCPtr(rend), rend, Pass.getCPtr(pass), pass, SWIGTYPE_p_Ogre__AutoParamDataSource.getCPtr(source), SWIGTYPE_p_Ogre__HashedVectorT_Ogre__Light_p_t.getCPtr(pLightList));
  }

  public void copyFrom(SubRenderState rhs) {
    RTShaderJNI.FFPLighting_copyFrom(swigCPtr, this, SubRenderState.getCPtr(rhs), rhs);
  }

  public boolean preAddToRenderState(RenderState renderState, Pass srcPass, Pass dstPass) {
    return RTShaderJNI.FFPLighting_preAddToRenderState(swigCPtr, this, RenderState.getCPtr(renderState), renderState, Pass.getCPtr(srcPass), srcPass, Pass.getCPtr(dstPass), dstPass);
  }

  public void setNormaliseEnabled(boolean enable) {
    RTShaderJNI.FFPLighting_setNormaliseEnabled(swigCPtr, this, enable);
  }

  public static void setType(String value) {
    RTShaderJNI.FFPLighting_Type_set(value);
  }

  public static String getType() {
    return RTShaderJNI.FFPLighting_Type_get();
  }

}
