/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class FFPTexturing extends SubRenderState {
  private transient long swigCPtr;

  protected FFPTexturing(long cPtr, boolean cMemoryOwn) {
    super(RTShaderJNI.FFPTexturing_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FFPTexturing obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTShaderJNI.delete_FFPTexturing(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FFPTexturing() {
    this(RTShaderJNI.new_FFPTexturing(), true);
  }

  public int getExecutionOrder() {
    return RTShaderJNI.FFPTexturing_getExecutionOrder(swigCPtr, this);
  }

  public void copyFrom(SubRenderState rhs) {
    RTShaderJNI.FFPTexturing_copyFrom(swigCPtr, this, SubRenderState.getCPtr(rhs), rhs);
  }

  public boolean preAddToRenderState(RenderState renderState, Pass srcPass, Pass dstPass) {
    return RTShaderJNI.FFPTexturing_preAddToRenderState(swigCPtr, this, RenderState.getCPtr(renderState), renderState, Pass.getCPtr(srcPass), srcPass, Pass.getCPtr(dstPass), dstPass);
  }

  public static void setType(String value) {
    RTShaderJNI.FFPTexturing_Type_set(value);
  }

  public static String getType() {
    return RTShaderJNI.FFPTexturing_Type_get();
  }

}
