/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum FilterOptions {
  FO_NONE,
  FO_POINT,
  FO_LINEAR,
  FO_ANISOTROPIC;

  public final int swigValue() {
    return swigValue;
  }

  public static FilterOptions swigToEnum(int swigValue) {
    FilterOptions[] swigValues = FilterOptions.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (FilterOptions swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + FilterOptions.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private FilterOptions() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private FilterOptions(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private FilterOptions(FilterOptions swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

