/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum FogMode {
  FOG_NONE,
  FOG_EXP,
  FOG_EXP2,
  FOG_LINEAR;

  public final int swigValue() {
    return swigValue;
  }

  public static FogMode swigToEnum(int swigValue) {
    FogMode[] swigValues = FogMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (FogMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + FogMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private FogMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private FogMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private FogMode(FogMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

