/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum FontType {
  FT_TRUETYPE(OgreOverlayJNI.FT_TRUETYPE_get()),
  FT_IMAGE(OgreOverlayJNI.FT_IMAGE_get());

  public final int swigValue() {
    return swigValue;
  }

  public static FontType swigToEnum(int swigValue) {
    FontType[] swigValues = FontType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (FontType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + FontType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private FontType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private FontType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private FontType(FontType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

