/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class FontManager extends ResourceManager {
  private transient long swigCPtr;

  protected FontManager(long cPtr, boolean cMemoryOwn) {
    super(OgreOverlayJNI.FontManager_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FontManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreOverlayJNI.delete_FontManager(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FontManager() {
    this(OgreOverlayJNI.new_FontManager(), true);
  }

  public FontPtr create(String name, String group, boolean isManual, ManualResourceLoader loader, NameValuePairList createParams) {
    return new FontPtr(OgreOverlayJNI.FontManager_create__SWIG_0(swigCPtr, this, name, group, isManual, ManualResourceLoader.getCPtr(loader), loader, NameValuePairList.getCPtr(createParams), createParams), true);
  }

  public FontPtr create(String name, String group, boolean isManual, ManualResourceLoader loader) {
    return new FontPtr(OgreOverlayJNI.FontManager_create__SWIG_1(swigCPtr, this, name, group, isManual, ManualResourceLoader.getCPtr(loader), loader), true);
  }

  public FontPtr create(String name, String group, boolean isManual) {
    return new FontPtr(OgreOverlayJNI.FontManager_create__SWIG_2(swigCPtr, this, name, group, isManual), true);
  }

  public FontPtr create(String name, String group) {
    return new FontPtr(OgreOverlayJNI.FontManager_create__SWIG_3(swigCPtr, this, name, group), true);
  }

  public FontPtr getByName(String name, String groupName) {
    return new FontPtr(OgreOverlayJNI.FontManager_getByName__SWIG_0(swigCPtr, this, name, groupName), true);
  }

  public FontPtr getByName(String name) {
    return new FontPtr(OgreOverlayJNI.FontManager_getByName__SWIG_1(swigCPtr, this, name), true);
  }

  public void parseScript(DataStreamPtr stream, String groupName) {
    OgreOverlayJNI.FontManager_parseScript(swigCPtr, this, DataStreamPtr.getCPtr(stream), stream, groupName);
  }

  public static FontManager getSingleton() {
    return new FontManager(OgreOverlayJNI.FontManager_getSingleton(), false);
  }

}
