/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum FrameBufferType {
  FBT_COLOUR(OgreJNI.FBT_COLOUR_get()),
  FBT_DEPTH(OgreJNI.FBT_DEPTH_get()),
  FBT_STENCIL(OgreJNI.FBT_STENCIL_get());

  public final int swigValue() {
    return swigValue;
  }

  public static FrameBufferType swigToEnum(int swigValue) {
    FrameBufferType[] swigValues = FrameBufferType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (FrameBufferType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + FrameBufferType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private FrameBufferType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private FrameBufferType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private FrameBufferType(FrameBufferType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

