/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class FrameListener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FrameListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FrameListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_FrameListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    OgreJNI.FrameListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    OgreJNI.FrameListener_change_ownership(this, swigCPtr, true);
  }

  public boolean frameStarted(FrameEvent evt) {
    return (getClass() == FrameListener.class) ? OgreJNI.FrameListener_frameStarted(swigCPtr, this, FrameEvent.getCPtr(evt), evt) : OgreJNI.FrameListener_frameStartedSwigExplicitFrameListener(swigCPtr, this, FrameEvent.getCPtr(evt), evt);
  }

  public boolean frameRenderingQueued(FrameEvent evt) {
    return (getClass() == FrameListener.class) ? OgreJNI.FrameListener_frameRenderingQueued(swigCPtr, this, FrameEvent.getCPtr(evt), evt) : OgreJNI.FrameListener_frameRenderingQueuedSwigExplicitFrameListener(swigCPtr, this, FrameEvent.getCPtr(evt), evt);
  }

  public boolean frameEnded(FrameEvent evt) {
    return (getClass() == FrameListener.class) ? OgreJNI.FrameListener_frameEnded(swigCPtr, this, FrameEvent.getCPtr(evt), evt) : OgreJNI.FrameListener_frameEndedSwigExplicitFrameListener(swigCPtr, this, FrameEvent.getCPtr(evt), evt);
  }

  public FrameListener() {
    this(OgreJNI.new_FrameListener(), true);
    OgreJNI.FrameListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
