/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class FrameTimeControllerValue extends FrameListener {
  private transient long swigCPtr;

  protected FrameTimeControllerValue(long cPtr, boolean cMemoryOwn) {
    super(OgreJNI.FrameTimeControllerValue_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FrameTimeControllerValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_FrameTimeControllerValue(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FrameTimeControllerValue() {
    this(OgreJNI.new_FrameTimeControllerValue(), true);
  }

  public static ControllerValueRealPtr create() {
    return new ControllerValueRealPtr(OgreJNI.FrameTimeControllerValue_create(), true);
  }

  public boolean frameEnded(FrameEvent evt) {
    return OgreJNI.FrameTimeControllerValue_frameEnded(swigCPtr, this, FrameEvent.getCPtr(evt), evt);
  }

  public boolean frameStarted(FrameEvent evt) {
    return OgreJNI.FrameTimeControllerValue_frameStarted(swigCPtr, this, FrameEvent.getCPtr(evt), evt);
  }

  public float getValue() {
    return OgreJNI.FrameTimeControllerValue_getValue(swigCPtr, this);
  }

  public void setValue(float value) {
    OgreJNI.FrameTimeControllerValue_setValue(swigCPtr, this, value);
  }

  public float getTimeFactor() {
    return OgreJNI.FrameTimeControllerValue_getTimeFactor(swigCPtr, this);
  }

  public void setTimeFactor(float tf) {
    OgreJNI.FrameTimeControllerValue_setTimeFactor(swigCPtr, this, tf);
  }

  public float getFrameDelay() {
    return OgreJNI.FrameTimeControllerValue_getFrameDelay(swigCPtr, this);
  }

  public void setFrameDelay(float fd) {
    OgreJNI.FrameTimeControllerValue_setFrameDelay(swigCPtr, this, fd);
  }

  public float getElapsedTime() {
    return OgreJNI.FrameTimeControllerValue_getElapsedTime(swigCPtr, this);
  }

  public void setElapsedTime(float elapsedTime) {
    OgreJNI.FrameTimeControllerValue_setElapsedTime(swigCPtr, this, elapsedTime);
  }

}
