/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum GpuParamVariability {
  GPV_GLOBAL(OgreJNI.GPV_GLOBAL_get()),
  GPV_PER_OBJECT(OgreJNI.GPV_PER_OBJECT_get()),
  GPV_LIGHTS(OgreJNI.GPV_LIGHTS_get()),
  GPV_PASS_ITERATION_NUMBER(OgreJNI.GPV_PASS_ITERATION_NUMBER_get()),
  GPV_ALL(OgreJNI.GPV_ALL_get());

  public final int swigValue() {
    return swigValue;
  }

  public static GpuParamVariability swigToEnum(int swigValue) {
    GpuParamVariability[] swigValues = GpuParamVariability.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (GpuParamVariability swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + GpuParamVariability.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private GpuParamVariability() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private GpuParamVariability(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private GpuParamVariability(GpuParamVariability swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

