/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum IlluminationStage {
  IS_AMBIENT,
  IS_PER_LIGHT,
  IS_DECAL,
  IS_UNKNOWN;

  public final int swigValue() {
    return swigValue;
  }

  public static IlluminationStage swigToEnum(int swigValue) {
    IlluminationStage[] swigValues = IlluminationStage.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IlluminationStage swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IlluminationStage.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IlluminationStage() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IlluminationStage(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IlluminationStage(IlluminationStage swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

