/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum InstanceManagerFlags {
  IM_USE16BIT(OgreJNI.IM_USE16BIT_get()),
  IM_VTFBESTFIT(OgreJNI.IM_VTFBESTFIT_get()),
  IM_VTFBONEMATRIXLOOKUP(OgreJNI.IM_VTFBONEMATRIXLOOKUP_get()),
  IM_USEBONEDUALQUATERNIONS(OgreJNI.IM_USEBONEDUALQUATERNIONS_get()),
  IM_USEONEWEIGHT(OgreJNI.IM_USEONEWEIGHT_get()),
  IM_FORCEONEWEIGHT(OgreJNI.IM_FORCEONEWEIGHT_get()),
  IM_USEALL(OgreJNI.IM_USEALL_get());

  public final int swigValue() {
    return swigValue;
  }

  public static InstanceManagerFlags swigToEnum(int swigValue) {
    InstanceManagerFlags[] swigValues = InstanceManagerFlags.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (InstanceManagerFlags swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + InstanceManagerFlags.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private InstanceManagerFlags() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private InstanceManagerFlags(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private InstanceManagerFlags(InstanceManagerFlags swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

