/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum LoggingLevel {
  LL_LOW(OgreJNI.LL_LOW_get()),
  LL_NORMAL(OgreJNI.LL_NORMAL_get()),
  LL_BOREME(OgreJNI.LL_BOREME_get());

  public final int swigValue() {
    return swigValue;
  }

  public static LoggingLevel swigToEnum(int swigValue) {
    LoggingLevel[] swigValues = LoggingLevel.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (LoggingLevel swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + LoggingLevel.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private LoggingLevel() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private LoggingLevel(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private LoggingLevel(LoggingLevel swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

