/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class MemoryDataStreamPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MemoryDataStreamPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MemoryDataStreamPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_MemoryDataStreamPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MemoryDataStreamPtr(SWIGTYPE_p_std__nullptr_t arg0) {
    this(OgreJNI.new_MemoryDataStreamPtr__SWIG_0(SWIGTYPE_p_std__nullptr_t.getCPtr(arg0)), true);
  }

  public MemoryDataStreamPtr() {
    this(OgreJNI.new_MemoryDataStreamPtr__SWIG_1(), true);
  }

  public MemoryDataStreamPtr(MemoryDataStreamPtr r) {
    this(OgreJNI.new_MemoryDataStreamPtr__SWIG_2(MemoryDataStreamPtr.getCPtr(r), r), true);
  }

  public MemoryDataStream __deref__() {
    long cPtr = OgreJNI.MemoryDataStreamPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new MemoryDataStream(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char getPtr() {
    long cPtr = OgreJNI.MemoryDataStreamPtr_getPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char getCurrentPtr() {
    long cPtr = OgreJNI.MemoryDataStreamPtr_getCurrentPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public long read(SWIGTYPE_p_void buf, long count) {
    return OgreJNI.MemoryDataStreamPtr_read(swigCPtr, this, SWIGTYPE_p_void.getCPtr(buf), count);
  }

  public long write(SWIGTYPE_p_void buf, long count) {
    return OgreJNI.MemoryDataStreamPtr_write(swigCPtr, this, SWIGTYPE_p_void.getCPtr(buf), count);
  }

  public long readLine(String buf, long maxCount, String delim) {
    return OgreJNI.MemoryDataStreamPtr_readLine__SWIG_0(swigCPtr, this, buf, maxCount, delim);
  }

  public long readLine(String buf, long maxCount) {
    return OgreJNI.MemoryDataStreamPtr_readLine__SWIG_1(swigCPtr, this, buf, maxCount);
  }

  public long skipLine(String delim) {
    return OgreJNI.MemoryDataStreamPtr_skipLine__SWIG_0(swigCPtr, this, delim);
  }

  public long skipLine() {
    return OgreJNI.MemoryDataStreamPtr_skipLine__SWIG_1(swigCPtr, this);
  }

  public void skip(int count) {
    OgreJNI.MemoryDataStreamPtr_skip(swigCPtr, this, count);
  }

  public void seek(long pos) {
    OgreJNI.MemoryDataStreamPtr_seek(swigCPtr, this, pos);
  }

  public long tell() {
    return OgreJNI.MemoryDataStreamPtr_tell(swigCPtr, this);
  }

  public boolean eof() {
    return OgreJNI.MemoryDataStreamPtr_eof(swigCPtr, this);
  }

  public void close() {
    OgreJNI.MemoryDataStreamPtr_close(swigCPtr, this);
  }

  public void setFreeOnClose(boolean free) {
    OgreJNI.MemoryDataStreamPtr_setFreeOnClose(swigCPtr, this, free);
  }

  public String getName() {
    return OgreJNI.MemoryDataStreamPtr_getName(swigCPtr, this);
  }

  public int getAccessMode() {
    return OgreJNI.MemoryDataStreamPtr_getAccessMode(swigCPtr, this);
  }

  public boolean isReadable() {
    return OgreJNI.MemoryDataStreamPtr_isReadable(swigCPtr, this);
  }

  public boolean isWriteable() {
    return OgreJNI.MemoryDataStreamPtr_isWriteable(swigCPtr, this);
  }

  public String getLine(boolean trimAfter) {
    return OgreJNI.MemoryDataStreamPtr_getLine__SWIG_0(swigCPtr, this, trimAfter);
  }

  public String getLine() {
    return OgreJNI.MemoryDataStreamPtr_getLine__SWIG_1(swigCPtr, this);
  }

  public String getAsString() {
    return OgreJNI.MemoryDataStreamPtr_getAsString(swigCPtr, this);
  }

  public long size() {
    return OgreJNI.MemoryDataStreamPtr_size(swigCPtr, this);
  }

}
