/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum OrientationMode {
  OR_DEGREE_0(OgreJNI.OR_DEGREE_0_get()),
  OR_DEGREE_90(OgreJNI.OR_DEGREE_90_get()),
  OR_DEGREE_180(OgreJNI.OR_DEGREE_180_get()),
  OR_DEGREE_270(OgreJNI.OR_DEGREE_270_get()),
  OR_PORTRAIT(OgreJNI.OR_PORTRAIT_get()),
  OR_LANDSCAPERIGHT(OgreJNI.OR_LANDSCAPERIGHT_get()),
  OR_LANDSCAPELEFT(OgreJNI.OR_LANDSCAPELEFT_get());

  public final int swigValue() {
    return swigValue;
  }

  public static OrientationMode swigToEnum(int swigValue) {
    OrientationMode[] swigValues = OrientationMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (OrientationMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + OrientationMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private OrientationMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private OrientationMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private OrientationMode(OrientationMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

