/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class OverlayElementPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OverlayElementPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OverlayElementPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreOverlayJNI.delete_OverlayElementPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OverlayElementPtr(SWIGTYPE_p_std__nullptr_t arg0) {
    this(OgreOverlayJNI.new_OverlayElementPtr__SWIG_0(SWIGTYPE_p_std__nullptr_t.getCPtr(arg0)), true);
  }

  public OverlayElementPtr() {
    this(OgreOverlayJNI.new_OverlayElementPtr__SWIG_1(), true);
  }

  public OverlayElementPtr(OverlayElementPtr r) {
    this(OgreOverlayJNI.new_OverlayElementPtr__SWIG_2(OverlayElementPtr.getCPtr(r), r), true);
  }

  public OverlayElement __deref__() {
    long cPtr = OgreOverlayJNI.OverlayElementPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new OverlayElement(cPtr, false);
  }

  public String getDEFAULT_RESOURCE_GROUP() {
    return OgreOverlayJNI.OverlayElementPtr_DEFAULT_RESOURCE_GROUP_get(swigCPtr, this);
  }

  public void initialise() {
    OgreOverlayJNI.OverlayElementPtr_initialise(swigCPtr, this);
  }

  public void _releaseManualHardwareResources() {
    OgreOverlayJNI.OverlayElementPtr__releaseManualHardwareResources(swigCPtr, this);
  }

  public void _restoreManualHardwareResources() {
    OgreOverlayJNI.OverlayElementPtr__restoreManualHardwareResources(swigCPtr, this);
  }

  public String getName() {
    return OgreOverlayJNI.OverlayElementPtr_getName(swigCPtr, this);
  }

  public void show() {
    OgreOverlayJNI.OverlayElementPtr_show(swigCPtr, this);
  }

  public void hide() {
    OgreOverlayJNI.OverlayElementPtr_hide(swigCPtr, this);
  }

  public boolean isVisible() {
    return OgreOverlayJNI.OverlayElementPtr_isVisible(swigCPtr, this);
  }

  public boolean isEnabled() {
    return OgreOverlayJNI.OverlayElementPtr_isEnabled(swigCPtr, this);
  }

  public void setEnabled(boolean b) {
    OgreOverlayJNI.OverlayElementPtr_setEnabled(swigCPtr, this, b);
  }

  public void setDimensions(float width, float height) {
    OgreOverlayJNI.OverlayElementPtr_setDimensions(swigCPtr, this, width, height);
  }

  public void setPosition(float left, float top) {
    OgreOverlayJNI.OverlayElementPtr_setPosition(swigCPtr, this, left, top);
  }

  public void setWidth(float width) {
    OgreOverlayJNI.OverlayElementPtr_setWidth(swigCPtr, this, width);
  }

  public float getWidth() {
    return OgreOverlayJNI.OverlayElementPtr_getWidth(swigCPtr, this);
  }

  public void setHeight(float height) {
    OgreOverlayJNI.OverlayElementPtr_setHeight(swigCPtr, this, height);
  }

  public float getHeight() {
    return OgreOverlayJNI.OverlayElementPtr_getHeight(swigCPtr, this);
  }

  public void setLeft(float left) {
    OgreOverlayJNI.OverlayElementPtr_setLeft(swigCPtr, this, left);
  }

  public float getLeft() {
    return OgreOverlayJNI.OverlayElementPtr_getLeft(swigCPtr, this);
  }

  public void setTop(float Top) {
    OgreOverlayJNI.OverlayElementPtr_setTop(swigCPtr, this, Top);
  }

  public float getTop() {
    return OgreOverlayJNI.OverlayElementPtr_getTop(swigCPtr, this);
  }

  public float _getLeft() {
    return OgreOverlayJNI.OverlayElementPtr__getLeft(swigCPtr, this);
  }

  public float _getTop() {
    return OgreOverlayJNI.OverlayElementPtr__getTop(swigCPtr, this);
  }

  public float _getWidth() {
    return OgreOverlayJNI.OverlayElementPtr__getWidth(swigCPtr, this);
  }

  public float _getHeight() {
    return OgreOverlayJNI.OverlayElementPtr__getHeight(swigCPtr, this);
  }

  public void _setLeft(float left) {
    OgreOverlayJNI.OverlayElementPtr__setLeft(swigCPtr, this, left);
  }

  public void _setTop(float top) {
    OgreOverlayJNI.OverlayElementPtr__setTop(swigCPtr, this, top);
  }

  public void _setWidth(float width) {
    OgreOverlayJNI.OverlayElementPtr__setWidth(swigCPtr, this, width);
  }

  public void _setHeight(float height) {
    OgreOverlayJNI.OverlayElementPtr__setHeight(swigCPtr, this, height);
  }

  public void _setPosition(float left, float top) {
    OgreOverlayJNI.OverlayElementPtr__setPosition(swigCPtr, this, left, top);
  }

  public void _setDimensions(float width, float height) {
    OgreOverlayJNI.OverlayElementPtr__setDimensions(swigCPtr, this, width, height);
  }

  public String getMaterialName() {
    return OgreOverlayJNI.OverlayElementPtr_getMaterialName(swigCPtr, this);
  }

  public void setMaterial(MaterialPtr mat) {
    OgreOverlayJNI.OverlayElementPtr_setMaterial(swigCPtr, this, MaterialPtr.getCPtr(mat), mat);
  }

  public void setMaterialName(String matName, String group) {
    OgreOverlayJNI.OverlayElementPtr_setMaterialName__SWIG_0(swigCPtr, this, matName, group);
  }

  public void setMaterialName(String matName) {
    OgreOverlayJNI.OverlayElementPtr_setMaterialName__SWIG_1(swigCPtr, this, matName);
  }

  public MaterialPtr getMaterial() {
    return new MaterialPtr(OgreOverlayJNI.OverlayElementPtr_getMaterial(swigCPtr, this), false);
  }

  public void getWorldTransforms(Matrix4 xform) {
    OgreOverlayJNI.OverlayElementPtr_getWorldTransforms(swigCPtr, this, Matrix4.getCPtr(xform), xform);
  }

  public void _positionsOutOfDate() {
    OgreOverlayJNI.OverlayElementPtr__positionsOutOfDate(swigCPtr, this);
  }

  public void _update() {
    OgreOverlayJNI.OverlayElementPtr__update(swigCPtr, this);
  }

  public void _updateFromParent() {
    OgreOverlayJNI.OverlayElementPtr__updateFromParent(swigCPtr, this);
  }

  public void _notifyParent(OverlayContainer parent, Overlay overlay) {
    OgreOverlayJNI.OverlayElementPtr__notifyParent(swigCPtr, this, OverlayContainer.getCPtr(parent), parent, Overlay.getCPtr(overlay), overlay);
  }

  public float _getDerivedLeft() {
    return OgreOverlayJNI.OverlayElementPtr__getDerivedLeft(swigCPtr, this);
  }

  public float _getDerivedTop() {
    return OgreOverlayJNI.OverlayElementPtr__getDerivedTop(swigCPtr, this);
  }

  public float _getRelativeWidth() {
    return OgreOverlayJNI.OverlayElementPtr__getRelativeWidth(swigCPtr, this);
  }

  public float _getRelativeHeight() {
    return OgreOverlayJNI.OverlayElementPtr__getRelativeHeight(swigCPtr, this);
  }

  public void _getClippingRegion(FloatRect clippingRegion) {
    OgreOverlayJNI.OverlayElementPtr__getClippingRegion(swigCPtr, this, FloatRect.getCPtr(clippingRegion), clippingRegion);
  }

  public int _notifyZOrder(int newZOrder) {
    return OgreOverlayJNI.OverlayElementPtr__notifyZOrder(swigCPtr, this, newZOrder);
  }

  public void _notifyWorldTransforms(Matrix4 xform) {
    OgreOverlayJNI.OverlayElementPtr__notifyWorldTransforms(swigCPtr, this, Matrix4.getCPtr(xform), xform);
  }

  public void _notifyViewport() {
    OgreOverlayJNI.OverlayElementPtr__notifyViewport(swigCPtr, this);
  }

  public void _updateRenderQueue(RenderQueue queue) {
    OgreOverlayJNI.OverlayElementPtr__updateRenderQueue(swigCPtr, this, RenderQueue.getCPtr(queue), queue);
  }

  public void visitRenderables(Renderable.Visitor visitor, boolean debugRenderables) {
    OgreOverlayJNI.OverlayElementPtr_visitRenderables__SWIG_0(swigCPtr, this, Renderable.Visitor.getCPtr(visitor), visitor, debugRenderables);
  }

  public void visitRenderables(Renderable.Visitor visitor) {
    OgreOverlayJNI.OverlayElementPtr_visitRenderables__SWIG_1(swigCPtr, this, Renderable.Visitor.getCPtr(visitor), visitor);
  }

  public String getTypeName() {
    return OgreOverlayJNI.OverlayElementPtr_getTypeName(swigCPtr, this);
  }

  public void setCaption(SWIGTYPE_p_UTFString text) {
    OgreOverlayJNI.OverlayElementPtr_setCaption(swigCPtr, this, SWIGTYPE_p_UTFString.getCPtr(text));
  }

  public SWIGTYPE_p_UTFString getCaption() {
    return new SWIGTYPE_p_UTFString(OgreOverlayJNI.OverlayElementPtr_getCaption(swigCPtr, this), false);
  }

  public void setColour(ColourValue col) {
    OgreOverlayJNI.OverlayElementPtr_setColour(swigCPtr, this, ColourValue.getCPtr(col), col);
  }

  public ColourValue getColour() {
    return new ColourValue(OgreOverlayJNI.OverlayElementPtr_getColour(swigCPtr, this), false);
  }

  public void setMetricsMode(GuiMetricsMode gmm) {
    OgreOverlayJNI.OverlayElementPtr_setMetricsMode(swigCPtr, this, gmm.swigValue());
  }

  public GuiMetricsMode getMetricsMode() {
    return GuiMetricsMode.swigToEnum(OgreOverlayJNI.OverlayElementPtr_getMetricsMode(swigCPtr, this));
  }

  public void setHorizontalAlignment(GuiHorizontalAlignment gha) {
    OgreOverlayJNI.OverlayElementPtr_setHorizontalAlignment(swigCPtr, this, gha.swigValue());
  }

  public GuiHorizontalAlignment getHorizontalAlignment() {
    return GuiHorizontalAlignment.swigToEnum(OgreOverlayJNI.OverlayElementPtr_getHorizontalAlignment(swigCPtr, this));
  }

  public void setVerticalAlignment(GuiVerticalAlignment gva) {
    OgreOverlayJNI.OverlayElementPtr_setVerticalAlignment(swigCPtr, this, gva.swigValue());
  }

  public GuiVerticalAlignment getVerticalAlignment() {
    return GuiVerticalAlignment.swigToEnum(OgreOverlayJNI.OverlayElementPtr_getVerticalAlignment(swigCPtr, this));
  }

  public boolean contains(float x, float y) {
    return OgreOverlayJNI.OverlayElementPtr_contains(swigCPtr, this, x, y);
  }

  public OverlayElement findElementAt(float x, float y) {
    long cPtr = OgreOverlayJNI.OverlayElementPtr_findElementAt(swigCPtr, this, x, y);
    return (cPtr == 0) ? null : new OverlayElement(cPtr, false);
  }

  public boolean isContainer() {
    return OgreOverlayJNI.OverlayElementPtr_isContainer(swigCPtr, this);
  }

  public boolean isKeyEnabled() {
    return OgreOverlayJNI.OverlayElementPtr_isKeyEnabled(swigCPtr, this);
  }

  public boolean isCloneable() {
    return OgreOverlayJNI.OverlayElementPtr_isCloneable(swigCPtr, this);
  }

  public void setCloneable(boolean c) {
    OgreOverlayJNI.OverlayElementPtr_setCloneable(swigCPtr, this, c);
  }

  public OverlayContainer getParent() {
    long cPtr = OgreOverlayJNI.OverlayElementPtr_getParent(swigCPtr, this);
    return (cPtr == 0) ? null : new OverlayContainer(cPtr, false);
  }

  public void _setParent(OverlayContainer parent) {
    OgreOverlayJNI.OverlayElementPtr__setParent(swigCPtr, this, OverlayContainer.getCPtr(parent), parent);
  }

  public int getZOrder() {
    return OgreOverlayJNI.OverlayElementPtr_getZOrder(swigCPtr, this);
  }

  public float getSquaredViewDepth(Camera cam) {
    return OgreOverlayJNI.OverlayElementPtr_getSquaredViewDepth(swigCPtr, this, Camera.getCPtr(cam), cam);
  }

  public SWIGTYPE_p_Ogre__HashedVectorT_Ogre__Light_p_t getLights() {
    return new SWIGTYPE_p_Ogre__HashedVectorT_Ogre__Light_p_t(OgreOverlayJNI.OverlayElementPtr_getLights(swigCPtr, this), false);
  }

  public void copyFromTemplate(OverlayElement templateOverlay) {
    OgreOverlayJNI.OverlayElementPtr_copyFromTemplate(swigCPtr, this, OverlayElement.getCPtr(templateOverlay), templateOverlay);
  }

  public OverlayElement clone(String instanceName) {
    long cPtr = OgreOverlayJNI.OverlayElementPtr_clone(swigCPtr, this, instanceName);
    return (cPtr == 0) ? null : new OverlayElement(cPtr, false);
  }

  public OverlayElement getSourceTemplate() {
    long cPtr = OgreOverlayJNI.OverlayElementPtr_getSourceTemplate(swigCPtr, this);
    return (cPtr == 0) ? null : new OverlayElement(cPtr, false);
  }

  public ParamDictionary getParamDictionary() {
    long cPtr = OgreOverlayJNI.OverlayElementPtr_getParamDictionary__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new ParamDictionary(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_Ogre__ParameterDef_t getParameters() {
    return new SWIGTYPE_p_std__vectorT_Ogre__ParameterDef_t(OgreOverlayJNI.OverlayElementPtr_getParameters(swigCPtr, this), false);
  }

  public boolean setParameter(String name, String value) {
    return OgreOverlayJNI.OverlayElementPtr_setParameter(swigCPtr, this, name, value);
  }

  public void setParameterList(NameValuePairList paramList) {
    OgreOverlayJNI.OverlayElementPtr_setParameterList(swigCPtr, this, NameValuePairList.getCPtr(paramList), paramList);
  }

  public String getParameter(String name) {
    return OgreOverlayJNI.OverlayElementPtr_getParameter(swigCPtr, this, name);
  }

  public void copyParametersTo(StringInterface dest) {
    OgreOverlayJNI.OverlayElementPtr_copyParametersTo(swigCPtr, this, StringInterface.getCPtr(dest), dest);
  }

  public void cleanupDictionary() {
    OgreOverlayJNI.OverlayElementPtr_cleanupDictionary(swigCPtr, this);
  }

  public Technique getTechnique() {
    long cPtr = OgreOverlayJNI.OverlayElementPtr_getTechnique(swigCPtr, this);
    return (cPtr == 0) ? null : new Technique(cPtr, false);
  }

  public void getRenderOperation(RenderOperation op) {
    OgreOverlayJNI.OverlayElementPtr_getRenderOperation(swigCPtr, this, RenderOperation.getCPtr(op), op);
  }

  public boolean preRender(SceneManager sm, RenderSystem rsys) {
    return OgreOverlayJNI.OverlayElementPtr_preRender(swigCPtr, this, SceneManager.getCPtr(sm), sm, RenderSystem.getCPtr(rsys), rsys);
  }

  public void postRender(SceneManager sm, RenderSystem rsys) {
    OgreOverlayJNI.OverlayElementPtr_postRender(swigCPtr, this, SceneManager.getCPtr(sm), sm, RenderSystem.getCPtr(rsys), rsys);
  }

  public int getNumWorldTransforms() {
    return OgreOverlayJNI.OverlayElementPtr_getNumWorldTransforms(swigCPtr, this);
  }

  public void setUseIdentityProjection(boolean useIdentityProjection) {
    OgreOverlayJNI.OverlayElementPtr_setUseIdentityProjection(swigCPtr, this, useIdentityProjection);
  }

  public boolean getUseIdentityProjection() {
    return OgreOverlayJNI.OverlayElementPtr_getUseIdentityProjection(swigCPtr, this);
  }

  public void setUseIdentityView(boolean useIdentityView) {
    OgreOverlayJNI.OverlayElementPtr_setUseIdentityView(swigCPtr, this, useIdentityView);
  }

  public boolean getUseIdentityView() {
    return OgreOverlayJNI.OverlayElementPtr_getUseIdentityView(swigCPtr, this);
  }

  public boolean getCastsShadows() {
    return OgreOverlayJNI.OverlayElementPtr_getCastsShadows(swigCPtr, this);
  }

  public void setCustomParameter(long index, Vector4 value) {
    OgreOverlayJNI.OverlayElementPtr_setCustomParameter(swigCPtr, this, index, Vector4.getCPtr(value), value);
  }

  public void removeCustomParameter(long index) {
    OgreOverlayJNI.OverlayElementPtr_removeCustomParameter(swigCPtr, this, index);
  }

  public boolean hasCustomParameter(long index) {
    return OgreOverlayJNI.OverlayElementPtr_hasCustomParameter(swigCPtr, this, index);
  }

  public Vector4 getCustomParameter(long index) {
    return new Vector4(OgreOverlayJNI.OverlayElementPtr_getCustomParameter(swigCPtr, this, index), false);
  }

  public void _updateCustomGpuParameter(GpuProgramParameters.AutoConstantEntry constantEntry, GpuProgramParameters params) {
    OgreOverlayJNI.OverlayElementPtr__updateCustomGpuParameter(swigCPtr, this, GpuProgramParameters.AutoConstantEntry.getCPtr(constantEntry), constantEntry, GpuProgramParameters.getCPtr(params), params);
  }

  public void setPolygonModeOverrideable(boolean override) {
    OgreOverlayJNI.OverlayElementPtr_setPolygonModeOverrideable(swigCPtr, this, override);
  }

  public boolean getPolygonModeOverrideable() {
    return OgreOverlayJNI.OverlayElementPtr_getPolygonModeOverrideable(swigCPtr, this);
  }

  public UserObjectBindings getUserObjectBindings() {
    return new UserObjectBindings(OgreOverlayJNI.OverlayElementPtr_getUserObjectBindings__SWIG_0(swigCPtr, this), false);
  }

  public SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Renderable__RenderSystemData_t getRenderSystemData() {
    return new SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Renderable__RenderSystemData_t(OgreOverlayJNI.OverlayElementPtr_getRenderSystemData(swigCPtr, this), false);
  }

  public void setRenderSystemData(SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Renderable__RenderSystemData_t val) {
    OgreOverlayJNI.OverlayElementPtr_setRenderSystemData(swigCPtr, this, SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Renderable__RenderSystemData_t.getCPtr(val));
  }

}
