/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class OverlayContainerPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OverlayContainerPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OverlayContainerPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreOverlayJNI.delete_OverlayContainerPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OverlayContainerPtr(SWIGTYPE_p_std__nullptr_t arg0) {
    this(OgreOverlayJNI.new_OverlayContainerPtr__SWIG_0(SWIGTYPE_p_std__nullptr_t.getCPtr(arg0)), true);
  }

  public OverlayContainerPtr() {
    this(OgreOverlayJNI.new_OverlayContainerPtr__SWIG_1(), true);
  }

  public OverlayContainerPtr(OverlayContainerPtr r) {
    this(OgreOverlayJNI.new_OverlayContainerPtr__SWIG_2(OverlayContainerPtr.getCPtr(r), r), true);
  }

  public OverlayContainer __deref__() {
    long cPtr = OgreOverlayJNI.OverlayContainerPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new OverlayContainer(cPtr, false);
  }

  public void addChild(OverlayElement elem) {
    OgreOverlayJNI.OverlayContainerPtr_addChild(swigCPtr, this, OverlayElement.getCPtr(elem), elem);
  }

  public void addChildImpl(OverlayElement elem) {
    OgreOverlayJNI.OverlayContainerPtr_addChildImpl__SWIG_0(swigCPtr, this, OverlayElement.getCPtr(elem), elem);
  }

  public void addChildImpl(OverlayContainer cont) {
    OgreOverlayJNI.OverlayContainerPtr_addChildImpl__SWIG_1(swigCPtr, this, OverlayContainer.getCPtr(cont), cont);
  }

  public void removeChild(String name) {
    OgreOverlayJNI.OverlayContainerPtr_removeChild(swigCPtr, this, name);
  }

  public OverlayElement getChild(String name) {
    long cPtr = OgreOverlayJNI.OverlayContainerPtr_getChild(swigCPtr, this, name);
    return (cPtr == 0) ? null : new OverlayElement(cPtr, false);
  }

  public void initialise() {
    OgreOverlayJNI.OverlayContainerPtr_initialise(swigCPtr, this);
  }

  public void _addChild(OverlayElement elem) {
    OgreOverlayJNI.OverlayContainerPtr__addChild(swigCPtr, this, OverlayElement.getCPtr(elem), elem);
  }

  public void _removeChild(OverlayElement elem) {
    OgreOverlayJNI.OverlayContainerPtr__removeChild__SWIG_0(swigCPtr, this, OverlayElement.getCPtr(elem), elem);
  }

  public void _removeChild(String name) {
    OgreOverlayJNI.OverlayContainerPtr__removeChild__SWIG_1(swigCPtr, this, name);
  }

  public SWIGTYPE_p_std__mapT_std__string_Ogre__OverlayElement_p_t getChildren() {
    return new SWIGTYPE_p_std__mapT_std__string_Ogre__OverlayElement_p_t(OgreOverlayJNI.OverlayContainerPtr_getChildren(swigCPtr, this), false);
  }

  public void _positionsOutOfDate() {
    OgreOverlayJNI.OverlayContainerPtr__positionsOutOfDate(swigCPtr, this);
  }

  public void _update() {
    OgreOverlayJNI.OverlayContainerPtr__update(swigCPtr, this);
  }

  public int _notifyZOrder(int newZOrder) {
    return OgreOverlayJNI.OverlayContainerPtr__notifyZOrder(swigCPtr, this, newZOrder);
  }

  public void _notifyViewport() {
    OgreOverlayJNI.OverlayContainerPtr__notifyViewport(swigCPtr, this);
  }

  public void _notifyWorldTransforms(Matrix4 xform) {
    OgreOverlayJNI.OverlayContainerPtr__notifyWorldTransforms(swigCPtr, this, Matrix4.getCPtr(xform), xform);
  }

  public void _notifyParent(OverlayContainer parent, Overlay overlay) {
    OgreOverlayJNI.OverlayContainerPtr__notifyParent(swigCPtr, this, OverlayContainer.getCPtr(parent), parent, Overlay.getCPtr(overlay), overlay);
  }

  public void _updateRenderQueue(RenderQueue queue) {
    OgreOverlayJNI.OverlayContainerPtr__updateRenderQueue(swigCPtr, this, RenderQueue.getCPtr(queue), queue);
  }

  public boolean isContainer() {
    return OgreOverlayJNI.OverlayContainerPtr_isContainer(swigCPtr, this);
  }

  public boolean isChildrenProcessEvents() {
    return OgreOverlayJNI.OverlayContainerPtr_isChildrenProcessEvents(swigCPtr, this);
  }

  public void setChildrenProcessEvents(boolean val) {
    OgreOverlayJNI.OverlayContainerPtr_setChildrenProcessEvents(swigCPtr, this, val);
  }

  public OverlayElement findElementAt(float x, float y) {
    long cPtr = OgreOverlayJNI.OverlayContainerPtr_findElementAt(swigCPtr, this, x, y);
    return (cPtr == 0) ? null : new OverlayElement(cPtr, false);
  }

  public void copyFromTemplate(OverlayElement templateOverlay) {
    OgreOverlayJNI.OverlayContainerPtr_copyFromTemplate(swigCPtr, this, OverlayElement.getCPtr(templateOverlay), templateOverlay);
  }

  public OverlayElement clone(String instanceName) {
    long cPtr = OgreOverlayJNI.OverlayContainerPtr_clone(swigCPtr, this, instanceName);
    return (cPtr == 0) ? null : new OverlayElement(cPtr, false);
  }

  public String getDEFAULT_RESOURCE_GROUP() {
    return OgreOverlayJNI.OverlayContainerPtr_DEFAULT_RESOURCE_GROUP_get(swigCPtr, this);
  }

  public void _releaseManualHardwareResources() {
    OgreOverlayJNI.OverlayContainerPtr__releaseManualHardwareResources(swigCPtr, this);
  }

  public void _restoreManualHardwareResources() {
    OgreOverlayJNI.OverlayContainerPtr__restoreManualHardwareResources(swigCPtr, this);
  }

  public String getName() {
    return OgreOverlayJNI.OverlayContainerPtr_getName(swigCPtr, this);
  }

  public void show() {
    OgreOverlayJNI.OverlayContainerPtr_show(swigCPtr, this);
  }

  public void hide() {
    OgreOverlayJNI.OverlayContainerPtr_hide(swigCPtr, this);
  }

  public boolean isVisible() {
    return OgreOverlayJNI.OverlayContainerPtr_isVisible(swigCPtr, this);
  }

  public boolean isEnabled() {
    return OgreOverlayJNI.OverlayContainerPtr_isEnabled(swigCPtr, this);
  }

  public void setEnabled(boolean b) {
    OgreOverlayJNI.OverlayContainerPtr_setEnabled(swigCPtr, this, b);
  }

  public void setDimensions(float width, float height) {
    OgreOverlayJNI.OverlayContainerPtr_setDimensions(swigCPtr, this, width, height);
  }

  public void setPosition(float left, float top) {
    OgreOverlayJNI.OverlayContainerPtr_setPosition(swigCPtr, this, left, top);
  }

  public void setWidth(float width) {
    OgreOverlayJNI.OverlayContainerPtr_setWidth(swigCPtr, this, width);
  }

  public float getWidth() {
    return OgreOverlayJNI.OverlayContainerPtr_getWidth(swigCPtr, this);
  }

  public void setHeight(float height) {
    OgreOverlayJNI.OverlayContainerPtr_setHeight(swigCPtr, this, height);
  }

  public float getHeight() {
    return OgreOverlayJNI.OverlayContainerPtr_getHeight(swigCPtr, this);
  }

  public void setLeft(float left) {
    OgreOverlayJNI.OverlayContainerPtr_setLeft(swigCPtr, this, left);
  }

  public float getLeft() {
    return OgreOverlayJNI.OverlayContainerPtr_getLeft(swigCPtr, this);
  }

  public void setTop(float Top) {
    OgreOverlayJNI.OverlayContainerPtr_setTop(swigCPtr, this, Top);
  }

  public float getTop() {
    return OgreOverlayJNI.OverlayContainerPtr_getTop(swigCPtr, this);
  }

  public float _getLeft() {
    return OgreOverlayJNI.OverlayContainerPtr__getLeft(swigCPtr, this);
  }

  public float _getTop() {
    return OgreOverlayJNI.OverlayContainerPtr__getTop(swigCPtr, this);
  }

  public float _getWidth() {
    return OgreOverlayJNI.OverlayContainerPtr__getWidth(swigCPtr, this);
  }

  public float _getHeight() {
    return OgreOverlayJNI.OverlayContainerPtr__getHeight(swigCPtr, this);
  }

  public void _setLeft(float left) {
    OgreOverlayJNI.OverlayContainerPtr__setLeft(swigCPtr, this, left);
  }

  public void _setTop(float top) {
    OgreOverlayJNI.OverlayContainerPtr__setTop(swigCPtr, this, top);
  }

  public void _setWidth(float width) {
    OgreOverlayJNI.OverlayContainerPtr__setWidth(swigCPtr, this, width);
  }

  public void _setHeight(float height) {
    OgreOverlayJNI.OverlayContainerPtr__setHeight(swigCPtr, this, height);
  }

  public void _setPosition(float left, float top) {
    OgreOverlayJNI.OverlayContainerPtr__setPosition(swigCPtr, this, left, top);
  }

  public void _setDimensions(float width, float height) {
    OgreOverlayJNI.OverlayContainerPtr__setDimensions(swigCPtr, this, width, height);
  }

  public String getMaterialName() {
    return OgreOverlayJNI.OverlayContainerPtr_getMaterialName(swigCPtr, this);
  }

  public void setMaterial(MaterialPtr mat) {
    OgreOverlayJNI.OverlayContainerPtr_setMaterial(swigCPtr, this, MaterialPtr.getCPtr(mat), mat);
  }

  public void setMaterialName(String matName, String group) {
    OgreOverlayJNI.OverlayContainerPtr_setMaterialName__SWIG_0(swigCPtr, this, matName, group);
  }

  public void setMaterialName(String matName) {
    OgreOverlayJNI.OverlayContainerPtr_setMaterialName__SWIG_1(swigCPtr, this, matName);
  }

  public MaterialPtr getMaterial() {
    return new MaterialPtr(OgreOverlayJNI.OverlayContainerPtr_getMaterial(swigCPtr, this), false);
  }

  public void getWorldTransforms(Matrix4 xform) {
    OgreOverlayJNI.OverlayContainerPtr_getWorldTransforms(swigCPtr, this, Matrix4.getCPtr(xform), xform);
  }

  public void _updateFromParent() {
    OgreOverlayJNI.OverlayContainerPtr__updateFromParent(swigCPtr, this);
  }

  public float _getDerivedLeft() {
    return OgreOverlayJNI.OverlayContainerPtr__getDerivedLeft(swigCPtr, this);
  }

  public float _getDerivedTop() {
    return OgreOverlayJNI.OverlayContainerPtr__getDerivedTop(swigCPtr, this);
  }

  public float _getRelativeWidth() {
    return OgreOverlayJNI.OverlayContainerPtr__getRelativeWidth(swigCPtr, this);
  }

  public float _getRelativeHeight() {
    return OgreOverlayJNI.OverlayContainerPtr__getRelativeHeight(swigCPtr, this);
  }

  public void _getClippingRegion(FloatRect clippingRegion) {
    OgreOverlayJNI.OverlayContainerPtr__getClippingRegion(swigCPtr, this, FloatRect.getCPtr(clippingRegion), clippingRegion);
  }

  public void visitRenderables(Renderable.Visitor visitor, boolean debugRenderables) {
    OgreOverlayJNI.OverlayContainerPtr_visitRenderables__SWIG_0(swigCPtr, this, Renderable.Visitor.getCPtr(visitor), visitor, debugRenderables);
  }

  public void visitRenderables(Renderable.Visitor visitor) {
    OgreOverlayJNI.OverlayContainerPtr_visitRenderables__SWIG_1(swigCPtr, this, Renderable.Visitor.getCPtr(visitor), visitor);
  }

  public String getTypeName() {
    return OgreOverlayJNI.OverlayContainerPtr_getTypeName(swigCPtr, this);
  }

  public void setCaption(SWIGTYPE_p_UTFString text) {
    OgreOverlayJNI.OverlayContainerPtr_setCaption(swigCPtr, this, SWIGTYPE_p_UTFString.getCPtr(text));
  }

  public SWIGTYPE_p_UTFString getCaption() {
    return new SWIGTYPE_p_UTFString(OgreOverlayJNI.OverlayContainerPtr_getCaption(swigCPtr, this), false);
  }

  public void setColour(ColourValue col) {
    OgreOverlayJNI.OverlayContainerPtr_setColour(swigCPtr, this, ColourValue.getCPtr(col), col);
  }

  public ColourValue getColour() {
    return new ColourValue(OgreOverlayJNI.OverlayContainerPtr_getColour(swigCPtr, this), false);
  }

  public void setMetricsMode(GuiMetricsMode gmm) {
    OgreOverlayJNI.OverlayContainerPtr_setMetricsMode(swigCPtr, this, gmm.swigValue());
  }

  public GuiMetricsMode getMetricsMode() {
    return GuiMetricsMode.swigToEnum(OgreOverlayJNI.OverlayContainerPtr_getMetricsMode(swigCPtr, this));
  }

  public void setHorizontalAlignment(GuiHorizontalAlignment gha) {
    OgreOverlayJNI.OverlayContainerPtr_setHorizontalAlignment(swigCPtr, this, gha.swigValue());
  }

  public GuiHorizontalAlignment getHorizontalAlignment() {
    return GuiHorizontalAlignment.swigToEnum(OgreOverlayJNI.OverlayContainerPtr_getHorizontalAlignment(swigCPtr, this));
  }

  public void setVerticalAlignment(GuiVerticalAlignment gva) {
    OgreOverlayJNI.OverlayContainerPtr_setVerticalAlignment(swigCPtr, this, gva.swigValue());
  }

  public GuiVerticalAlignment getVerticalAlignment() {
    return GuiVerticalAlignment.swigToEnum(OgreOverlayJNI.OverlayContainerPtr_getVerticalAlignment(swigCPtr, this));
  }

  public boolean contains(float x, float y) {
    return OgreOverlayJNI.OverlayContainerPtr_contains(swigCPtr, this, x, y);
  }

  public boolean isKeyEnabled() {
    return OgreOverlayJNI.OverlayContainerPtr_isKeyEnabled(swigCPtr, this);
  }

  public boolean isCloneable() {
    return OgreOverlayJNI.OverlayContainerPtr_isCloneable(swigCPtr, this);
  }

  public void setCloneable(boolean c) {
    OgreOverlayJNI.OverlayContainerPtr_setCloneable(swigCPtr, this, c);
  }

  public OverlayContainer getParent() {
    long cPtr = OgreOverlayJNI.OverlayContainerPtr_getParent(swigCPtr, this);
    return (cPtr == 0) ? null : new OverlayContainer(cPtr, false);
  }

  public void _setParent(OverlayContainer parent) {
    OgreOverlayJNI.OverlayContainerPtr__setParent(swigCPtr, this, OverlayContainer.getCPtr(parent), parent);
  }

  public int getZOrder() {
    return OgreOverlayJNI.OverlayContainerPtr_getZOrder(swigCPtr, this);
  }

  public float getSquaredViewDepth(Camera cam) {
    return OgreOverlayJNI.OverlayContainerPtr_getSquaredViewDepth(swigCPtr, this, Camera.getCPtr(cam), cam);
  }

  public SWIGTYPE_p_Ogre__HashedVectorT_Ogre__Light_p_t getLights() {
    return new SWIGTYPE_p_Ogre__HashedVectorT_Ogre__Light_p_t(OgreOverlayJNI.OverlayContainerPtr_getLights(swigCPtr, this), false);
  }

  public OverlayElement getSourceTemplate() {
    long cPtr = OgreOverlayJNI.OverlayContainerPtr_getSourceTemplate(swigCPtr, this);
    return (cPtr == 0) ? null : new OverlayElement(cPtr, false);
  }

  public ParamDictionary getParamDictionary() {
    long cPtr = OgreOverlayJNI.OverlayContainerPtr_getParamDictionary__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new ParamDictionary(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_Ogre__ParameterDef_t getParameters() {
    return new SWIGTYPE_p_std__vectorT_Ogre__ParameterDef_t(OgreOverlayJNI.OverlayContainerPtr_getParameters(swigCPtr, this), false);
  }

  public boolean setParameter(String name, String value) {
    return OgreOverlayJNI.OverlayContainerPtr_setParameter(swigCPtr, this, name, value);
  }

  public void setParameterList(NameValuePairList paramList) {
    OgreOverlayJNI.OverlayContainerPtr_setParameterList(swigCPtr, this, NameValuePairList.getCPtr(paramList), paramList);
  }

  public String getParameter(String name) {
    return OgreOverlayJNI.OverlayContainerPtr_getParameter(swigCPtr, this, name);
  }

  public void copyParametersTo(StringInterface dest) {
    OgreOverlayJNI.OverlayContainerPtr_copyParametersTo(swigCPtr, this, StringInterface.getCPtr(dest), dest);
  }

  public void cleanupDictionary() {
    OgreOverlayJNI.OverlayContainerPtr_cleanupDictionary(swigCPtr, this);
  }

  public Technique getTechnique() {
    long cPtr = OgreOverlayJNI.OverlayContainerPtr_getTechnique(swigCPtr, this);
    return (cPtr == 0) ? null : new Technique(cPtr, false);
  }

  public void getRenderOperation(RenderOperation op) {
    OgreOverlayJNI.OverlayContainerPtr_getRenderOperation(swigCPtr, this, RenderOperation.getCPtr(op), op);
  }

  public boolean preRender(SceneManager sm, RenderSystem rsys) {
    return OgreOverlayJNI.OverlayContainerPtr_preRender(swigCPtr, this, SceneManager.getCPtr(sm), sm, RenderSystem.getCPtr(rsys), rsys);
  }

  public void postRender(SceneManager sm, RenderSystem rsys) {
    OgreOverlayJNI.OverlayContainerPtr_postRender(swigCPtr, this, SceneManager.getCPtr(sm), sm, RenderSystem.getCPtr(rsys), rsys);
  }

  public int getNumWorldTransforms() {
    return OgreOverlayJNI.OverlayContainerPtr_getNumWorldTransforms(swigCPtr, this);
  }

  public void setUseIdentityProjection(boolean useIdentityProjection) {
    OgreOverlayJNI.OverlayContainerPtr_setUseIdentityProjection(swigCPtr, this, useIdentityProjection);
  }

  public boolean getUseIdentityProjection() {
    return OgreOverlayJNI.OverlayContainerPtr_getUseIdentityProjection(swigCPtr, this);
  }

  public void setUseIdentityView(boolean useIdentityView) {
    OgreOverlayJNI.OverlayContainerPtr_setUseIdentityView(swigCPtr, this, useIdentityView);
  }

  public boolean getUseIdentityView() {
    return OgreOverlayJNI.OverlayContainerPtr_getUseIdentityView(swigCPtr, this);
  }

  public boolean getCastsShadows() {
    return OgreOverlayJNI.OverlayContainerPtr_getCastsShadows(swigCPtr, this);
  }

  public void setCustomParameter(long index, Vector4 value) {
    OgreOverlayJNI.OverlayContainerPtr_setCustomParameter(swigCPtr, this, index, Vector4.getCPtr(value), value);
  }

  public void removeCustomParameter(long index) {
    OgreOverlayJNI.OverlayContainerPtr_removeCustomParameter(swigCPtr, this, index);
  }

  public boolean hasCustomParameter(long index) {
    return OgreOverlayJNI.OverlayContainerPtr_hasCustomParameter(swigCPtr, this, index);
  }

  public Vector4 getCustomParameter(long index) {
    return new Vector4(OgreOverlayJNI.OverlayContainerPtr_getCustomParameter(swigCPtr, this, index), false);
  }

  public void _updateCustomGpuParameter(GpuProgramParameters.AutoConstantEntry constantEntry, GpuProgramParameters params) {
    OgreOverlayJNI.OverlayContainerPtr__updateCustomGpuParameter(swigCPtr, this, GpuProgramParameters.AutoConstantEntry.getCPtr(constantEntry), constantEntry, GpuProgramParameters.getCPtr(params), params);
  }

  public void setPolygonModeOverrideable(boolean override) {
    OgreOverlayJNI.OverlayContainerPtr_setPolygonModeOverrideable(swigCPtr, this, override);
  }

  public boolean getPolygonModeOverrideable() {
    return OgreOverlayJNI.OverlayContainerPtr_getPolygonModeOverrideable(swigCPtr, this);
  }

  public UserObjectBindings getUserObjectBindings() {
    return new UserObjectBindings(OgreOverlayJNI.OverlayContainerPtr_getUserObjectBindings__SWIG_0(swigCPtr, this), false);
  }

  public SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Renderable__RenderSystemData_t getRenderSystemData() {
    return new SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Renderable__RenderSystemData_t(OgreOverlayJNI.OverlayContainerPtr_getRenderSystemData(swigCPtr, this), false);
  }

  public void setRenderSystemData(SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Renderable__RenderSystemData_t val) {
    OgreOverlayJNI.OverlayContainerPtr_setRenderSystemData(swigCPtr, this, SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Renderable__RenderSystemData_t.getCPtr(val));
  }

}
