/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class ParticleAffectorPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParticleAffectorPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParticleAffectorPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_ParticleAffectorPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ParticleAffectorPtr(SWIGTYPE_p_std__nullptr_t arg0) {
    this(OgreJNI.new_ParticleAffectorPtr__SWIG_0(SWIGTYPE_p_std__nullptr_t.getCPtr(arg0)), true);
  }

  public ParticleAffectorPtr() {
    this(OgreJNI.new_ParticleAffectorPtr__SWIG_1(), true);
  }

  public ParticleAffectorPtr(ParticleAffectorPtr r) {
    this(OgreJNI.new_ParticleAffectorPtr__SWIG_2(ParticleAffectorPtr.getCPtr(r), r), true);
  }

  public ParticleAffector __deref__() {
    long cPtr = OgreJNI.ParticleAffectorPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new ParticleAffector(cPtr, false);
  }

  public void _initParticle(Particle pParticle) {
    OgreJNI.ParticleAffectorPtr__initParticle(swigCPtr, this, Particle.getCPtr(pParticle), pParticle);
  }

  public void _affectParticles(ParticleSystem pSystem, float timeElapsed) {
    OgreJNI.ParticleAffectorPtr__affectParticles(swigCPtr, this, ParticleSystem.getCPtr(pSystem), pSystem, timeElapsed);
  }

  public ParamDictionary getParamDictionary() {
    long cPtr = OgreJNI.ParticleAffectorPtr_getParamDictionary__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new ParamDictionary(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_Ogre__ParameterDef_t getParameters() {
    return new SWIGTYPE_p_std__vectorT_Ogre__ParameterDef_t(OgreJNI.ParticleAffectorPtr_getParameters(swigCPtr, this), false);
  }

  public boolean setParameter(String name, String value) {
    return OgreJNI.ParticleAffectorPtr_setParameter(swigCPtr, this, name, value);
  }

  public void setParameterList(NameValuePairList paramList) {
    OgreJNI.ParticleAffectorPtr_setParameterList(swigCPtr, this, NameValuePairList.getCPtr(paramList), paramList);
  }

  public String getParameter(String name) {
    return OgreJNI.ParticleAffectorPtr_getParameter(swigCPtr, this, name);
  }

  public void copyParametersTo(StringInterface dest) {
    OgreJNI.ParticleAffectorPtr_copyParametersTo(swigCPtr, this, StringInterface.getCPtr(dest), dest);
  }

  public void cleanupDictionary() {
    OgreJNI.ParticleAffectorPtr_cleanupDictionary(swigCPtr, this);
  }

}
