/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class PassthroughControllerFunction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PassthroughControllerFunction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PassthroughControllerFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_PassthroughControllerFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PassthroughControllerFunction(boolean deltaInput) {
    this(OgreJNI.new_PassthroughControllerFunction__SWIG_0(deltaInput), true);
  }

  public PassthroughControllerFunction() {
    this(OgreJNI.new_PassthroughControllerFunction__SWIG_1(), true);
  }

  public static ControllerFunctionPtr create(boolean deltaInput) {
    return new ControllerFunctionPtr(OgreJNI.PassthroughControllerFunction_create__SWIG_0(deltaInput), true);
  }

  public static ControllerFunctionPtr create() {
    return new ControllerFunctionPtr(OgreJNI.PassthroughControllerFunction_create__SWIG_1(), true);
  }

  public float calculate(float source) {
    return OgreJNI.PassthroughControllerFunction_calculate(swigCPtr, this, source);
  }

}
