/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class PerPixelLighting extends FFPLighting {
  private transient long swigCPtr;

  protected PerPixelLighting(long cPtr, boolean cMemoryOwn) {
    super(RTShaderJNI.PerPixelLighting_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PerPixelLighting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTShaderJNI.delete_PerPixelLighting(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static void setType(String value) {
    RTShaderJNI.PerPixelLighting_Type_set(value);
  }

  public static String getType() {
    return RTShaderJNI.PerPixelLighting_Type_get();
  }

  public PerPixelLighting() {
    this(RTShaderJNI.new_PerPixelLighting(), true);
  }

}
