/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class PixelCountLodStrategyBase extends LodStrategy {
  private transient long swigCPtr;

  protected PixelCountLodStrategyBase(long cPtr, boolean cMemoryOwn) {
    super(OgreJNI.PixelCountLodStrategyBase_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PixelCountLodStrategyBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_PixelCountLodStrategyBase(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PixelCountLodStrategyBase(String name) {
    this(OgreJNI.new_PixelCountLodStrategyBase(name), true);
  }

  public float getBaseValue() {
    return OgreJNI.PixelCountLodStrategyBase_getBaseValue(swigCPtr, this);
  }

  public float transformBias(float factor) {
    return OgreJNI.PixelCountLodStrategyBase_transformBias(swigCPtr, this, factor);
  }

  public int getIndex(float value, SWIGTYPE_p_std__vectorT_Ogre__MeshLodUsage_t meshLodUsageList) {
    return OgreJNI.PixelCountLodStrategyBase_getIndex__SWIG_0(swigCPtr, this, value, SWIGTYPE_p_std__vectorT_Ogre__MeshLodUsage_t.getCPtr(meshLodUsageList));
  }

  public int getIndex(float value, SWIGTYPE_p_std__vectorT_float_t materialLodValueList) {
    return OgreJNI.PixelCountLodStrategyBase_getIndex__SWIG_1(swigCPtr, this, value, SWIGTYPE_p_std__vectorT_float_t.getCPtr(materialLodValueList));
  }

  public void sort(SWIGTYPE_p_std__vectorT_Ogre__MeshLodUsage_t meshLodUsageList) {
    OgreJNI.PixelCountLodStrategyBase_sort(swigCPtr, this, SWIGTYPE_p_std__vectorT_Ogre__MeshLodUsage_t.getCPtr(meshLodUsageList));
  }

  public boolean isSorted(SWIGTYPE_p_std__vectorT_float_t values) {
    return OgreJNI.PixelCountLodStrategyBase_isSorted(swigCPtr, this, SWIGTYPE_p_std__vectorT_float_t.getCPtr(values));
  }

}
