/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum PixelFormatFlags {
  PFF_HASALPHA(OgreJNI.PFF_HASALPHA_get()),
  PFF_COMPRESSED(OgreJNI.PFF_COMPRESSED_get()),
  PFF_FLOAT(OgreJNI.PFF_FLOAT_get()),
  PFF_DEPTH(OgreJNI.PFF_DEPTH_get()),
  PFF_NATIVEENDIAN(OgreJNI.PFF_NATIVEENDIAN_get()),
  PFF_LUMINANCE(OgreJNI.PFF_LUMINANCE_get()),
  PFF_INTEGER(OgreJNI.PFF_INTEGER_get());

  public final int swigValue() {
    return swigValue;
  }

  public static PixelFormatFlags swigToEnum(int swigValue) {
    PixelFormatFlags[] swigValues = PixelFormatFlags.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (PixelFormatFlags swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + PixelFormatFlags.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private PixelFormatFlags() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private PixelFormatFlags(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private PixelFormatFlags(PixelFormatFlags swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

