/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class PSSMShadowCameraSetupPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PSSMShadowCameraSetupPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PSSMShadowCameraSetupPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_PSSMShadowCameraSetupPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PSSMShadowCameraSetupPtr(SWIGTYPE_p_std__nullptr_t arg0) {
    this(OgreJNI.new_PSSMShadowCameraSetupPtr__SWIG_0(SWIGTYPE_p_std__nullptr_t.getCPtr(arg0)), true);
  }

  public PSSMShadowCameraSetupPtr() {
    this(OgreJNI.new_PSSMShadowCameraSetupPtr__SWIG_1(), true);
  }

  public PSSMShadowCameraSetupPtr(PSSMShadowCameraSetupPtr r) {
    this(OgreJNI.new_PSSMShadowCameraSetupPtr__SWIG_2(PSSMShadowCameraSetupPtr.getCPtr(r), r), true);
  }

  public PSSMShadowCameraSetup __deref__() {
    long cPtr = OgreJNI.PSSMShadowCameraSetupPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new PSSMShadowCameraSetup(cPtr, false);
  }

  public ShadowCameraSetupPtr create() {
    return new ShadowCameraSetupPtr(OgreJNI.PSSMShadowCameraSetupPtr_create(swigCPtr, this), true);
  }

  public void calculateSplitPoints(long splitCount, float nearDist, float farDist, float lambda) {
    OgreJNI.PSSMShadowCameraSetupPtr_calculateSplitPoints__SWIG_0(swigCPtr, this, splitCount, nearDist, farDist, lambda);
  }

  public void calculateSplitPoints(long splitCount, float nearDist, float farDist) {
    OgreJNI.PSSMShadowCameraSetupPtr_calculateSplitPoints__SWIG_1(swigCPtr, this, splitCount, nearDist, farDist);
  }

  public void setSplitPoints(SWIGTYPE_p_std__vectorT_float_t newSplitPoints) {
    OgreJNI.PSSMShadowCameraSetupPtr_setSplitPoints(swigCPtr, this, SWIGTYPE_p_std__vectorT_float_t.getCPtr(newSplitPoints));
  }

  public void setOptimalAdjustFactor(long splitIndex, float factor) {
    OgreJNI.PSSMShadowCameraSetupPtr_setOptimalAdjustFactor(swigCPtr, this, splitIndex, factor);
  }

  public void setSplitPadding(float pad) {
    OgreJNI.PSSMShadowCameraSetupPtr_setSplitPadding(swigCPtr, this, pad);
  }

  public float getSplitPadding() {
    return OgreJNI.PSSMShadowCameraSetupPtr_getSplitPadding(swigCPtr, this);
  }

  public long getSplitCount() {
    return OgreJNI.PSSMShadowCameraSetupPtr_getSplitCount(swigCPtr, this);
  }

  public void getShadowCamera(SceneManager sm, Camera cam, Viewport vp, Light light, Camera texCam, long iteration) {
    OgreJNI.PSSMShadowCameraSetupPtr_getShadowCamera(swigCPtr, this, SceneManager.getCPtr(sm), sm, Camera.getCPtr(cam), cam, Viewport.getCPtr(vp), vp, Light.getCPtr(light), light, Camera.getCPtr(texCam), texCam, iteration);
  }

  public SWIGTYPE_p_std__vectorT_float_t getSplitPoints() {
    return new SWIGTYPE_p_std__vectorT_float_t(OgreJNI.PSSMShadowCameraSetupPtr_getSplitPoints(swigCPtr, this), false);
  }

  public float getOptimalAdjustFactor(long splitIndex) {
    return OgreJNI.PSSMShadowCameraSetupPtr_getOptimalAdjustFactor__SWIG_0(swigCPtr, this, splitIndex);
  }

  public float getOptimalAdjustFactor() {
    return OgreJNI.PSSMShadowCameraSetupPtr_getOptimalAdjustFactor__SWIG_1(swigCPtr, this);
  }

  public void setUseSimpleOptimalAdjust(boolean s) {
    OgreJNI.PSSMShadowCameraSetupPtr_setUseSimpleOptimalAdjust(swigCPtr, this, s);
  }

  public boolean getUseSimpleOptimalAdjust() {
    return OgreJNI.PSSMShadowCameraSetupPtr_getUseSimpleOptimalAdjust(swigCPtr, this);
  }

  public void setCameraLightDirectionThreshold(Degree angle) {
    OgreJNI.PSSMShadowCameraSetupPtr_setCameraLightDirectionThreshold(swigCPtr, this, Degree.getCPtr(angle), angle);
  }

  public Degree getCameraLightDirectionThreshold() {
    return new Degree(OgreJNI.PSSMShadowCameraSetupPtr_getCameraLightDirectionThreshold(swigCPtr, this), true);
  }

  public void setUseAggressiveFocusRegion(boolean aggressive) {
    OgreJNI.PSSMShadowCameraSetupPtr_setUseAggressiveFocusRegion(swigCPtr, this, aggressive);
  }

  public boolean getUseAggressiveFocusRegion() {
    return OgreJNI.PSSMShadowCameraSetupPtr_getUseAggressiveFocusRegion(swigCPtr, this);
  }

}
