/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class QueuedRenderableVisitor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected QueuedRenderableVisitor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QueuedRenderableVisitor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_QueuedRenderableVisitor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void visit(RenderablePass rp) {
    OgreJNI.QueuedRenderableVisitor_visit__SWIG_0(swigCPtr, this, RenderablePass.getCPtr(rp), rp);
  }

  public void visit(Pass p, SWIGTYPE_p_std__vectorT_Ogre__Renderable_p_t rs) {
    OgreJNI.QueuedRenderableVisitor_visit__SWIG_1(swigCPtr, this, Pass.getCPtr(p), p, SWIGTYPE_p_std__vectorT_Ogre__Renderable_p_t.getCPtr(rs));
  }

}
