/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class RayTestResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RayTestResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RayTestResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_RayTestResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RayTestResult() {
    this(OgreJNI.new_RayTestResult__SWIG_0(), true);
  }

  public RayTestResult(boolean first, float second) {
    this(OgreJNI.new_RayTestResult__SWIG_1(first, second), true);
  }

  public RayTestResult(RayTestResult p) {
    this(OgreJNI.new_RayTestResult__SWIG_2(RayTestResult.getCPtr(p), p), true);
  }

  public void setFirst(boolean value) {
    OgreJNI.RayTestResult_first_set(swigCPtr, this, value);
  }

  public boolean getFirst() {
    return OgreJNI.RayTestResult_first_get(swigCPtr, this);
  }

  public void setSecond(float value) {
    OgreJNI.RayTestResult_second_set(swigCPtr, this, value);
  }

  public float getSecond() {
    return OgreJNI.RayTestResult_second_get(swigCPtr, this);
  }

}
