/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class RenderState {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RenderState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RenderState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTShaderJNI.delete_RenderState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RenderState() {
    this(RTShaderJNI.new_RenderState(), true);
  }

  public void reset() {
    RTShaderJNI.RenderState_reset(swigCPtr, this);
  }

  public void addTemplateSubRenderState(SubRenderState subRenderState) {
    RTShaderJNI.RenderState_addTemplateSubRenderState(swigCPtr, this, SubRenderState.getCPtr(subRenderState), subRenderState);
  }

  public void removeTemplateSubRenderState(SubRenderState subRenderState) {
    RTShaderJNI.RenderState_removeTemplateSubRenderState(swigCPtr, this, SubRenderState.getCPtr(subRenderState), subRenderState);
  }

  public SWIGTYPE_p_std__vectorT_Ogre__RTShader__SubRenderState_p_t getTemplateSubRenderStateList() {
    return new SWIGTYPE_p_std__vectorT_Ogre__RTShader__SubRenderState_p_t(RTShaderJNI.RenderState_getTemplateSubRenderStateList(swigCPtr, this), false);
  }

  public void setLightCount(Vector3i lightCount) {
    RTShaderJNI.RenderState_setLightCount(swigCPtr, this, Vector3i.getCPtr(lightCount), lightCount);
  }

  public Vector3i getLightCount() {
    return new Vector3i(RTShaderJNI.RenderState_getLightCount(swigCPtr, this), false);
  }

  public void setLightCountAutoUpdate(boolean autoUpdate) {
    RTShaderJNI.RenderState_setLightCountAutoUpdate(swigCPtr, this, autoUpdate);
  }

  public boolean getLightCountAutoUpdate() {
    return RTShaderJNI.RenderState_getLightCountAutoUpdate(swigCPtr, this);
  }

}
