/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class Resource extends StringInterface {
  private transient long swigCPtr;

  protected Resource(long cPtr, boolean cMemoryOwn) {
    super(OgreJNI.Resource_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Resource obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_Resource(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  static public class Listener {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Listener(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Listener obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgreJNI.delete_Resource_Listener(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    protected void swigDirectorDisconnect() {
      swigCMemOwn = false;
      delete();
    }
  
    public void swigReleaseOwnership() {
      swigCMemOwn = false;
      OgreJNI.Resource_Listener_change_ownership(this, swigCPtr, false);
    }
  
    public void swigTakeOwnership() {
      swigCMemOwn = true;
      OgreJNI.Resource_Listener_change_ownership(this, swigCPtr, true);
    }
  
    public void loadingComplete(Resource arg0) {
      if (getClass() == Listener.class) OgreJNI.Resource_Listener_loadingComplete(swigCPtr, this, Resource.getCPtr(arg0), arg0); else OgreJNI.Resource_Listener_loadingCompleteSwigExplicitListener(swigCPtr, this, Resource.getCPtr(arg0), arg0);
    }
  
    public void preparingComplete(Resource arg0) {
      if (getClass() == Listener.class) OgreJNI.Resource_Listener_preparingComplete(swigCPtr, this, Resource.getCPtr(arg0), arg0); else OgreJNI.Resource_Listener_preparingCompleteSwigExplicitListener(swigCPtr, this, Resource.getCPtr(arg0), arg0);
    }
  
    public void unloadingComplete(Resource arg0) {
      if (getClass() == Listener.class) OgreJNI.Resource_Listener_unloadingComplete(swigCPtr, this, Resource.getCPtr(arg0), arg0); else OgreJNI.Resource_Listener_unloadingCompleteSwigExplicitListener(swigCPtr, this, Resource.getCPtr(arg0), arg0);
    }
  
    public Listener() {
      this(OgreJNI.new_Resource_Listener(), true);
      OgreJNI.Resource_Listener_director_connect(this, swigCPtr, swigCMemOwn, true);
    }
  
  }

  public void prepare(boolean backgroundThread) {
    OgreJNI.Resource_prepare__SWIG_0(swigCPtr, this, backgroundThread);
  }

  public void prepare() {
    OgreJNI.Resource_prepare__SWIG_1(swigCPtr, this);
  }

  public void load(boolean backgroundThread) {
    OgreJNI.Resource_load__SWIG_0(swigCPtr, this, backgroundThread);
  }

  public void load() {
    OgreJNI.Resource_load__SWIG_1(swigCPtr, this);
  }

  public void reload(Resource.LoadingFlags flags) {
    OgreJNI.Resource_reload__SWIG_0(swigCPtr, this, flags.swigValue());
  }

  public void reload() {
    OgreJNI.Resource_reload__SWIG_1(swigCPtr, this);
  }

  public boolean isReloadable() {
    return OgreJNI.Resource_isReloadable(swigCPtr, this);
  }

  public boolean isManuallyLoaded() {
    return OgreJNI.Resource_isManuallyLoaded(swigCPtr, this);
  }

  public void unload() {
    OgreJNI.Resource_unload(swigCPtr, this);
  }

  public long getSize() {
    return OgreJNI.Resource_getSize(swigCPtr, this);
  }

  public void touch() {
    OgreJNI.Resource_touch(swigCPtr, this);
  }

  public String getName() {
    return OgreJNI.Resource_getName(swigCPtr, this);
  }

  public long getHandle() {
    return OgreJNI.Resource_getHandle(swigCPtr, this);
  }

  public boolean isPrepared() {
    return OgreJNI.Resource_isPrepared(swigCPtr, this);
  }

  public boolean isLoaded() {
    return OgreJNI.Resource_isLoaded(swigCPtr, this);
  }

  public boolean isLoading() {
    return OgreJNI.Resource_isLoading(swigCPtr, this);
  }

  public Resource.LoadingState getLoadingState() {
    return Resource.LoadingState.swigToEnum(OgreJNI.Resource_getLoadingState(swigCPtr, this));
  }

  public boolean isBackgroundLoaded() {
    return OgreJNI.Resource_isBackgroundLoaded(swigCPtr, this);
  }

  public void setBackgroundLoaded(boolean bl) {
    OgreJNI.Resource_setBackgroundLoaded(swigCPtr, this, bl);
  }

  public void escalateLoading() {
    OgreJNI.Resource_escalateLoading(swigCPtr, this);
  }

  public void addListener(Resource.Listener lis) {
    OgreJNI.Resource_addListener(swigCPtr, this, Resource.Listener.getCPtr(lis), lis);
  }

  public void removeListener(Resource.Listener lis) {
    OgreJNI.Resource_removeListener(swigCPtr, this, Resource.Listener.getCPtr(lis), lis);
  }

  public String getGroup() {
    return OgreJNI.Resource_getGroup(swigCPtr, this);
  }

  public void changeGroupOwnership(String newGroup) {
    OgreJNI.Resource_changeGroupOwnership(swigCPtr, this, newGroup);
  }

  public ResourceManager getCreator() {
    long cPtr = OgreJNI.Resource_getCreator(swigCPtr, this);
    return (cPtr == 0) ? null : new ResourceManager(cPtr, false);
  }

  public String getOrigin() {
    return OgreJNI.Resource_getOrigin(swigCPtr, this);
  }

  public void _notifyOrigin(String origin) {
    OgreJNI.Resource__notifyOrigin(swigCPtr, this, origin);
  }

  public long getStateCount() {
    return OgreJNI.Resource_getStateCount(swigCPtr, this);
  }

  public void _dirtyState() {
    OgreJNI.Resource__dirtyState(swigCPtr, this);
  }

  public void _fireLoadingComplete(boolean wasBackgroundLoaded) {
    OgreJNI.Resource__fireLoadingComplete(swigCPtr, this, wasBackgroundLoaded);
  }

  public void _firePreparingComplete(boolean wasBackgroundLoaded) {
    OgreJNI.Resource__firePreparingComplete(swigCPtr, this, wasBackgroundLoaded);
  }

  public void _fireUnloadingComplete() {
    OgreJNI.Resource__fireUnloadingComplete(swigCPtr, this);
  }

  public long calculateSize() {
    return OgreJNI.Resource_calculateSize(swigCPtr, this);
  }

  public enum LoadingState {
    LOADSTATE_UNLOADED,
    LOADSTATE_LOADING,
    LOADSTATE_LOADED,
    LOADSTATE_UNLOADING,
    LOADSTATE_PREPARED,
    LOADSTATE_PREPARING;

    public final int swigValue() {
      return swigValue;
    }

    public static LoadingState swigToEnum(int swigValue) {
      LoadingState[] swigValues = LoadingState.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (LoadingState swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + LoadingState.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private LoadingState() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private LoadingState(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private LoadingState(LoadingState swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

  public enum LoadingFlags {
    LF_DEFAULT(OgreJNI.Resource_LF_DEFAULT_get()),
    LF_INCLUDE_NON_RELOADABLE(OgreJNI.Resource_LF_INCLUDE_NON_RELOADABLE_get()),
    LF_ONLY_UNREFERENCED(OgreJNI.Resource_LF_ONLY_UNREFERENCED_get()),
    LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE(OgreJNI.Resource_LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE_get()),
    LF_PRESERVE_STATE(OgreJNI.Resource_LF_PRESERVE_STATE_get());

    public final int swigValue() {
      return swigValue;
    }

    public static LoadingFlags swigToEnum(int swigValue) {
      LoadingFlags[] swigValues = LoadingFlags.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (LoadingFlags swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + LoadingFlags.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private LoadingFlags() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private LoadingFlags(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private LoadingFlags(LoadingFlags swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

}
