/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class ScaleControllerFunction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ScaleControllerFunction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScaleControllerFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_ScaleControllerFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ScaleControllerFunction(float scalefactor, boolean deltaInput) {
    this(OgreJNI.new_ScaleControllerFunction(scalefactor, deltaInput), true);
  }

  public static ControllerFunctionPtr create(float scalefactor, boolean deltaInput) {
    return new ControllerFunctionPtr(OgreJNI.ScaleControllerFunction_create__SWIG_0(scalefactor, deltaInput), true);
  }

  public static ControllerFunctionPtr create(float scalefactor) {
    return new ControllerFunctionPtr(OgreJNI.ScaleControllerFunction_create__SWIG_1(scalefactor), true);
  }

  public float calculate(float source) {
    return OgreJNI.ScaleControllerFunction_calculate(swigCPtr, this, source);
  }

}
