/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class SceneQueryResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SceneQueryResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SceneQueryResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_SceneQueryResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMovables(SWIGTYPE_p_std__listT_Ogre__MovableObject_p_t value) {
    OgreJNI.SceneQueryResult_movables_set(swigCPtr, this, SWIGTYPE_p_std__listT_Ogre__MovableObject_p_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__listT_Ogre__MovableObject_p_t getMovables() {
    long cPtr = OgreJNI.SceneQueryResult_movables_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__listT_Ogre__MovableObject_p_t(cPtr, false);
  }

  public void setWorldFragments(SWIGTYPE_p_std__listT_Ogre__SceneQuery__WorldFragment_p_t value) {
    OgreJNI.SceneQueryResult_worldFragments_set(swigCPtr, this, SWIGTYPE_p_std__listT_Ogre__SceneQuery__WorldFragment_p_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__listT_Ogre__SceneQuery__WorldFragment_p_t getWorldFragments() {
    long cPtr = OgreJNI.SceneQueryResult_worldFragments_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__listT_Ogre__SceneQuery__WorldFragment_p_t(cPtr, false);
  }

  public SceneQueryResult() {
    this(OgreJNI.new_SceneQueryResult(), true);
  }

}
