/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum SceneBlendType {
  SBT_TRANSPARENT_ALPHA,
  SBT_TRANSPARENT_COLOUR,
  SBT_ADD,
  SBT_MODULATE,
  SBT_REPLACE;

  public final int swigValue() {
    return swigValue;
  }

  public static SceneBlendType swigToEnum(int swigValue) {
    SceneBlendType[] swigValues = SceneBlendType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (SceneBlendType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + SceneBlendType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private SceneBlendType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private SceneBlendType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private SceneBlendType(SceneBlendType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

