/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum SceneType {
  ST_GENERIC(OgreJNI.ST_GENERIC_get()),
  ST_EXTERIOR_CLOSE(OgreJNI.ST_EXTERIOR_CLOSE_get()),
  ST_EXTERIOR_FAR(OgreJNI.ST_EXTERIOR_FAR_get()),
  ST_EXTERIOR_REAL_FAR(OgreJNI.ST_EXTERIOR_REAL_FAR_get()),
  ST_INTERIOR(OgreJNI.ST_INTERIOR_get());

  public final int swigValue() {
    return swigValue;
  }

  public static SceneType swigToEnum(int swigValue) {
    SceneType[] swigValues = SceneType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (SceneType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + SceneType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private SceneType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private SceneType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private SceneType(SceneType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

