/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class ScreenRatioPixelCountLodStrategy extends PixelCountLodStrategyBase {
  private transient long swigCPtr;

  protected ScreenRatioPixelCountLodStrategy(long cPtr, boolean cMemoryOwn) {
    super(OgreJNI.ScreenRatioPixelCountLodStrategy_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScreenRatioPixelCountLodStrategy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_ScreenRatioPixelCountLodStrategy(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ScreenRatioPixelCountLodStrategy() {
    this(OgreJNI.new_ScreenRatioPixelCountLodStrategy(), true);
  }

  public static ScreenRatioPixelCountLodStrategy getSingleton() {
    return new ScreenRatioPixelCountLodStrategy(OgreJNI.ScreenRatioPixelCountLodStrategy_getSingleton(), false);
  }

}
