/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class SelectMenu extends Widget {
  private transient long swigCPtr;

  protected SelectMenu(long cPtr, boolean cMemoryOwn) {
    super(BitesJNI.SelectMenu_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SelectMenu obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BitesJNI.delete_SelectMenu(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SelectMenu(String name, SWIGTYPE_p_Ogre__DisplayString caption, float width, float boxWidth, long maxItemsShown) {
    this(BitesJNI.new_SelectMenu(name, SWIGTYPE_p_Ogre__DisplayString.getCPtr(caption), width, boxWidth, maxItemsShown), true);
  }

  public void copyItemsFrom(SelectMenu other) {
    BitesJNI.SelectMenu_copyItemsFrom(swigCPtr, this, SelectMenu.getCPtr(other), other);
  }

  public boolean isExpanded() {
    return BitesJNI.SelectMenu_isExpanded(swigCPtr, this);
  }

  public SWIGTYPE_p_Ogre__DisplayString getCaption() {
    return new SWIGTYPE_p_Ogre__DisplayString(BitesJNI.SelectMenu_getCaption(swigCPtr, this), false);
  }

  public void setCaption(SWIGTYPE_p_Ogre__DisplayString caption) {
    BitesJNI.SelectMenu_setCaption(swigCPtr, this, SWIGTYPE_p_Ogre__DisplayString.getCPtr(caption));
  }

  public StringVector getItems() {
    return new StringVector(BitesJNI.SelectMenu_getItems(swigCPtr, this), false);
  }

  public long getNumItems() {
    return BitesJNI.SelectMenu_getNumItems(swigCPtr, this);
  }

  public void setItems(StringVector items) {
    BitesJNI.SelectMenu_setItems(swigCPtr, this, StringVector.getCPtr(items), items);
  }

  public void addItem(SWIGTYPE_p_Ogre__DisplayString item) {
    BitesJNI.SelectMenu_addItem(swigCPtr, this, SWIGTYPE_p_Ogre__DisplayString.getCPtr(item));
  }

  public void insertItem(long index, SWIGTYPE_p_Ogre__DisplayString item) {
    BitesJNI.SelectMenu_insertItem(swigCPtr, this, index, SWIGTYPE_p_Ogre__DisplayString.getCPtr(item));
  }

  public void removeItem(SWIGTYPE_p_Ogre__DisplayString item) {
    BitesJNI.SelectMenu_removeItem__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__DisplayString.getCPtr(item));
  }

  public void removeItem(long index) {
    BitesJNI.SelectMenu_removeItem__SWIG_1(swigCPtr, this, index);
  }

  public void clearItems() {
    BitesJNI.SelectMenu_clearItems(swigCPtr, this);
  }

  public void selectItem(long index, boolean notifyListener) {
    BitesJNI.SelectMenu_selectItem__SWIG_0(swigCPtr, this, index, notifyListener);
  }

  public void selectItem(long index) {
    BitesJNI.SelectMenu_selectItem__SWIG_1(swigCPtr, this, index);
  }

  public boolean containsItem(SWIGTYPE_p_Ogre__DisplayString item) {
    return BitesJNI.SelectMenu_containsItem(swigCPtr, this, SWIGTYPE_p_Ogre__DisplayString.getCPtr(item));
  }

  public void selectItem(SWIGTYPE_p_Ogre__DisplayString item, boolean notifyListener) {
    BitesJNI.SelectMenu_selectItem__SWIG_2(swigCPtr, this, SWIGTYPE_p_Ogre__DisplayString.getCPtr(item), notifyListener);
  }

  public void selectItem(SWIGTYPE_p_Ogre__DisplayString item) {
    BitesJNI.SelectMenu_selectItem__SWIG_3(swigCPtr, this, SWIGTYPE_p_Ogre__DisplayString.getCPtr(item));
  }

  public SWIGTYPE_p_Ogre__DisplayString getSelectedItem() {
    return new SWIGTYPE_p_Ogre__DisplayString(BitesJNI.SelectMenu_getSelectedItem(swigCPtr, this), true);
  }

  public int getSelectionIndex() {
    return BitesJNI.SelectMenu_getSelectionIndex(swigCPtr, this);
  }

  public void _cursorPressed(Vector2 cursorPos) {
    BitesJNI.SelectMenu__cursorPressed(swigCPtr, this, Vector2.getCPtr(cursorPos), cursorPos);
  }

  public void _cursorReleased(Vector2 cursorPos) {
    BitesJNI.SelectMenu__cursorReleased(swigCPtr, this, Vector2.getCPtr(cursorPos), cursorPos);
  }

  public void _cursorMoved(Vector2 cursorPos, float wheelDelta) {
    BitesJNI.SelectMenu__cursorMoved(swigCPtr, this, Vector2.getCPtr(cursorPos), cursorPos, wheelDelta);
  }

  public void _focusLost() {
    BitesJNI.SelectMenu__focusLost(swigCPtr, this);
  }

}
