/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class Serializer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Serializer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Serializer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_Serializer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Serializer() {
    this(OgreJNI.new_Serializer(), true);
  }

  public enum Endian {
    ENDIAN_NATIVE,
    ENDIAN_BIG,
    ENDIAN_LITTLE;

    public final int swigValue() {
      return swigValue;
    }

    public static Endian swigToEnum(int swigValue) {
      Endian[] swigValues = Endian.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (Endian swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + Endian.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private Endian() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private Endian(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private Endian(Endian swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

}
