/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class SGScriptTranslator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SGScriptTranslator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SGScriptTranslator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTShaderJNI.delete_SGScriptTranslator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SGScriptTranslator() {
    this(RTShaderJNI.new_SGScriptTranslator(), true);
  }

  public void translate(ScriptCompiler compiler, SWIGTYPE_p_Ogre__SharedPtrT_Ogre__AbstractNode_t node) {
    RTShaderJNI.SGScriptTranslator_translate(swigCPtr, this, ScriptCompiler.getCPtr(compiler), compiler, SWIGTYPE_p_Ogre__SharedPtrT_Ogre__AbstractNode_t.getCPtr(node));
  }

  public SubRenderState getGeneratedSubRenderState(String typeName) {
    long cPtr = RTShaderJNI.SGScriptTranslator_getGeneratedSubRenderState(swigCPtr, this, typeName);
    return (cPtr == 0) ? null : new SubRenderState(cPtr, false);
  }

}
