/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum ShadowRenderableFlags {
  SRF_INCLUDE_LIGHT_CAP(OgreJNI.SRF_INCLUDE_LIGHT_CAP_get()),
  SRF_INCLUDE_DARK_CAP(OgreJNI.SRF_INCLUDE_DARK_CAP_get()),
  SRF_EXTRUDE_TO_INFINITY(OgreJNI.SRF_EXTRUDE_TO_INFINITY_get());

  public final int swigValue() {
    return swigValue;
  }

  public static ShadowRenderableFlags swigToEnum(int swigValue) {
    ShadowRenderableFlags[] swigValues = ShadowRenderableFlags.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ShadowRenderableFlags swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ShadowRenderableFlags.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ShadowRenderableFlags() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ShadowRenderableFlags(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ShadowRenderableFlags(ShadowRenderableFlags swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

