/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class SkeletonInstancePtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SkeletonInstancePtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SkeletonInstancePtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_SkeletonInstancePtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SkeletonInstancePtr(SWIGTYPE_p_std__nullptr_t arg0) {
    this(OgreJNI.new_SkeletonInstancePtr__SWIG_0(SWIGTYPE_p_std__nullptr_t.getCPtr(arg0)), true);
  }

  public SkeletonInstancePtr() {
    this(OgreJNI.new_SkeletonInstancePtr__SWIG_1(), true);
  }

  public SkeletonInstancePtr(SkeletonInstancePtr r) {
    this(OgreJNI.new_SkeletonInstancePtr__SWIG_2(SkeletonInstancePtr.getCPtr(r), r), true);
  }

  public SkeletonInstance __deref__() {
    long cPtr = OgreJNI.SkeletonInstancePtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new SkeletonInstance(cPtr, false);
  }

  public int getNumAnimations() {
    return OgreJNI.SkeletonInstancePtr_getNumAnimations(swigCPtr, this);
  }

  public Animation getAnimation(int index) {
    long cPtr = OgreJNI.SkeletonInstancePtr_getAnimation__SWIG_0(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Animation(cPtr, false);
  }

  public Animation getAnimation(String name, SWIGTYPE_p_p_Ogre__LinkedSkeletonAnimationSource linker) {
    long cPtr = OgreJNI.SkeletonInstancePtr_getAnimation__SWIG_1(swigCPtr, this, name, SWIGTYPE_p_p_Ogre__LinkedSkeletonAnimationSource.getCPtr(linker));
    return (cPtr == 0) ? null : new Animation(cPtr, false);
  }

  public Animation getAnimation(String name) {
    long cPtr = OgreJNI.SkeletonInstancePtr_getAnimation__SWIG_2(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Animation(cPtr, false);
  }

  public Animation _getAnimationImpl(String name, SWIGTYPE_p_p_Ogre__LinkedSkeletonAnimationSource linker) {
    long cPtr = OgreJNI.SkeletonInstancePtr__getAnimationImpl__SWIG_0(swigCPtr, this, name, SWIGTYPE_p_p_Ogre__LinkedSkeletonAnimationSource.getCPtr(linker));
    return (cPtr == 0) ? null : new Animation(cPtr, false);
  }

  public Animation _getAnimationImpl(String name) {
    long cPtr = OgreJNI.SkeletonInstancePtr__getAnimationImpl__SWIG_1(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Animation(cPtr, false);
  }

  public Animation createAnimation(String name, float length) {
    long cPtr = OgreJNI.SkeletonInstancePtr_createAnimation(swigCPtr, this, name, length);
    return (cPtr == 0) ? null : new Animation(cPtr, false);
  }

  public void removeAnimation(String name) {
    OgreJNI.SkeletonInstancePtr_removeAnimation(swigCPtr, this, name);
  }

  public SWIGTYPE_p_Ogre__TagPoint createTagPointOnBone(Bone bone, Quaternion offsetOrientation, Vector3 offsetPosition) {
    long cPtr = OgreJNI.SkeletonInstancePtr_createTagPointOnBone__SWIG_0(swigCPtr, this, Bone.getCPtr(bone), bone, Quaternion.getCPtr(offsetOrientation), offsetOrientation, Vector3.getCPtr(offsetPosition), offsetPosition);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__TagPoint(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__TagPoint createTagPointOnBone(Bone bone, Quaternion offsetOrientation) {
    long cPtr = OgreJNI.SkeletonInstancePtr_createTagPointOnBone__SWIG_1(swigCPtr, this, Bone.getCPtr(bone), bone, Quaternion.getCPtr(offsetOrientation), offsetOrientation);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__TagPoint(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__TagPoint createTagPointOnBone(Bone bone) {
    long cPtr = OgreJNI.SkeletonInstancePtr_createTagPointOnBone__SWIG_2(swigCPtr, this, Bone.getCPtr(bone), bone);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__TagPoint(cPtr, false);
  }

  public void freeTagPoint(SWIGTYPE_p_Ogre__TagPoint tagPoint) {
    OgreJNI.SkeletonInstancePtr_freeTagPoint(swigCPtr, this, SWIGTYPE_p_Ogre__TagPoint.getCPtr(tagPoint));
  }

  public void addLinkedSkeletonAnimationSource(String skelName, float scale) {
    OgreJNI.SkeletonInstancePtr_addLinkedSkeletonAnimationSource__SWIG_0(swigCPtr, this, skelName, scale);
  }

  public void addLinkedSkeletonAnimationSource(String skelName) {
    OgreJNI.SkeletonInstancePtr_addLinkedSkeletonAnimationSource__SWIG_1(swigCPtr, this, skelName);
  }

  public void removeAllLinkedSkeletonAnimationSources() {
    OgreJNI.SkeletonInstancePtr_removeAllLinkedSkeletonAnimationSources(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_Ogre__LinkedSkeletonAnimationSource_t getLinkedSkeletonAnimationSources() {
    return new SWIGTYPE_p_std__vectorT_Ogre__LinkedSkeletonAnimationSource_t(OgreJNI.SkeletonInstancePtr_getLinkedSkeletonAnimationSources(swigCPtr, this), false);
  }

  public void _initAnimationState(AnimationStateSet animSet) {
    OgreJNI.SkeletonInstancePtr__initAnimationState(swigCPtr, this, AnimationStateSet.getCPtr(animSet), animSet);
  }

  public void _refreshAnimationState(AnimationStateSet animSet) {
    OgreJNI.SkeletonInstancePtr__refreshAnimationState(swigCPtr, this, AnimationStateSet.getCPtr(animSet), animSet);
  }

  public String getName() {
    return OgreJNI.SkeletonInstancePtr_getName(swigCPtr, this);
  }

  public long getHandle() {
    return OgreJNI.SkeletonInstancePtr_getHandle(swigCPtr, this);
  }

  public String getGroup() {
    return OgreJNI.SkeletonInstancePtr_getGroup(swigCPtr, this);
  }

  public Bone createBone() {
    long cPtr = OgreJNI.SkeletonInstancePtr_createBone__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public Bone createBone(int handle) {
    long cPtr = OgreJNI.SkeletonInstancePtr_createBone__SWIG_1(swigCPtr, this, handle);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public Bone createBone(String name) {
    long cPtr = OgreJNI.SkeletonInstancePtr_createBone__SWIG_2(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public Bone createBone(String name, int handle) {
    long cPtr = OgreJNI.SkeletonInstancePtr_createBone__SWIG_3(swigCPtr, this, name, handle);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public int getNumBones() {
    return OgreJNI.SkeletonInstancePtr_getNumBones(swigCPtr, this);
  }

  public BoneList getRootBones() {
    return new BoneList(OgreJNI.SkeletonInstancePtr_getRootBones(swigCPtr, this), false);
  }

  public BoneList getBones() {
    return new BoneList(OgreJNI.SkeletonInstancePtr_getBones(swigCPtr, this), false);
  }

  public Bone getBone(int handle) {
    long cPtr = OgreJNI.SkeletonInstancePtr_getBone__SWIG_0(swigCPtr, this, handle);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public Bone getBone(String name) {
    long cPtr = OgreJNI.SkeletonInstancePtr_getBone__SWIG_1(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public boolean hasBone(String name) {
    return OgreJNI.SkeletonInstancePtr_hasBone(swigCPtr, this, name);
  }

  public void setBindingPose() {
    OgreJNI.SkeletonInstancePtr_setBindingPose(swigCPtr, this);
  }

  public void reset(boolean resetManualBones) {
    OgreJNI.SkeletonInstancePtr_reset__SWIG_0(swigCPtr, this, resetManualBones);
  }

  public void reset() {
    OgreJNI.SkeletonInstancePtr_reset__SWIG_1(swigCPtr, this);
  }

  public boolean hasAnimation(String name) {
    return OgreJNI.SkeletonInstancePtr_hasAnimation(swigCPtr, this, name);
  }

  public void setAnimationState(AnimationStateSet animSet) {
    OgreJNI.SkeletonInstancePtr_setAnimationState(swigCPtr, this, AnimationStateSet.getCPtr(animSet), animSet);
  }

  public void _getBoneMatrices(Affine3 pMatrices) {
    OgreJNI.SkeletonInstancePtr__getBoneMatrices(swigCPtr, this, Affine3.getCPtr(pMatrices), pMatrices);
  }

  public SkeletonAnimationBlendMode getBlendMode() {
    return SkeletonAnimationBlendMode.swigToEnum(OgreJNI.SkeletonInstancePtr_getBlendMode(swigCPtr, this));
  }

  public void setBlendMode(SkeletonAnimationBlendMode state) {
    OgreJNI.SkeletonInstancePtr_setBlendMode(swigCPtr, this, state.swigValue());
  }

  public void _updateTransforms() {
    OgreJNI.SkeletonInstancePtr__updateTransforms(swigCPtr, this);
  }

  public void optimiseAllAnimations(boolean preservingIdentityNodeTracks) {
    OgreJNI.SkeletonInstancePtr_optimiseAllAnimations__SWIG_0(swigCPtr, this, preservingIdentityNodeTracks);
  }

  public void optimiseAllAnimations() {
    OgreJNI.SkeletonInstancePtr_optimiseAllAnimations__SWIG_1(swigCPtr, this);
  }

  public void _notifyManualBonesDirty() {
    OgreJNI.SkeletonInstancePtr__notifyManualBonesDirty(swigCPtr, this);
  }

  public void _notifyManualBoneStateChange(Bone bone) {
    OgreJNI.SkeletonInstancePtr__notifyManualBoneStateChange(swigCPtr, this, Bone.getCPtr(bone), bone);
  }

  public boolean getManualBonesDirty() {
    return OgreJNI.SkeletonInstancePtr_getManualBonesDirty(swigCPtr, this);
  }

  public boolean hasManualBones() {
    return OgreJNI.SkeletonInstancePtr_hasManualBones(swigCPtr, this);
  }

  public void _mergeSkeletonAnimations(Skeleton source, SWIGTYPE_p_std__vectorT_unsigned_short_t boneHandleMap, StringVector animations) {
    OgreJNI.SkeletonInstancePtr__mergeSkeletonAnimations__SWIG_0(swigCPtr, this, Skeleton.getCPtr(source), source, SWIGTYPE_p_std__vectorT_unsigned_short_t.getCPtr(boneHandleMap), StringVector.getCPtr(animations), animations);
  }

  public void _mergeSkeletonAnimations(Skeleton source, SWIGTYPE_p_std__vectorT_unsigned_short_t boneHandleMap) {
    OgreJNI.SkeletonInstancePtr__mergeSkeletonAnimations__SWIG_1(swigCPtr, this, Skeleton.getCPtr(source), source, SWIGTYPE_p_std__vectorT_unsigned_short_t.getCPtr(boneHandleMap));
  }

  public void _buildMapBoneByHandle(Skeleton source, SWIGTYPE_p_std__vectorT_unsigned_short_t boneHandleMap) {
    OgreJNI.SkeletonInstancePtr__buildMapBoneByHandle(swigCPtr, this, Skeleton.getCPtr(source), source, SWIGTYPE_p_std__vectorT_unsigned_short_t.getCPtr(boneHandleMap));
  }

  public void _buildMapBoneByName(Skeleton source, SWIGTYPE_p_std__vectorT_unsigned_short_t boneHandleMap) {
    OgreJNI.SkeletonInstancePtr__buildMapBoneByName(swigCPtr, this, Skeleton.getCPtr(source), source, SWIGTYPE_p_std__vectorT_unsigned_short_t.getCPtr(boneHandleMap));
  }

  public void prepare(boolean backgroundThread) {
    OgreJNI.SkeletonInstancePtr_prepare__SWIG_0(swigCPtr, this, backgroundThread);
  }

  public void prepare() {
    OgreJNI.SkeletonInstancePtr_prepare__SWIG_1(swigCPtr, this);
  }

  public void load(boolean backgroundThread) {
    OgreJNI.SkeletonInstancePtr_load__SWIG_0(swigCPtr, this, backgroundThread);
  }

  public void load() {
    OgreJNI.SkeletonInstancePtr_load__SWIG_1(swigCPtr, this);
  }

  public void reload(Resource.LoadingFlags flags) {
    OgreJNI.SkeletonInstancePtr_reload__SWIG_0(swigCPtr, this, flags.swigValue());
  }

  public void reload() {
    OgreJNI.SkeletonInstancePtr_reload__SWIG_1(swigCPtr, this);
  }

  public boolean isReloadable() {
    return OgreJNI.SkeletonInstancePtr_isReloadable(swigCPtr, this);
  }

  public boolean isManuallyLoaded() {
    return OgreJNI.SkeletonInstancePtr_isManuallyLoaded(swigCPtr, this);
  }

  public void unload() {
    OgreJNI.SkeletonInstancePtr_unload(swigCPtr, this);
  }

  public long getSize() {
    return OgreJNI.SkeletonInstancePtr_getSize(swigCPtr, this);
  }

  public void touch() {
    OgreJNI.SkeletonInstancePtr_touch(swigCPtr, this);
  }

  public boolean isPrepared() {
    return OgreJNI.SkeletonInstancePtr_isPrepared(swigCPtr, this);
  }

  public boolean isLoaded() {
    return OgreJNI.SkeletonInstancePtr_isLoaded(swigCPtr, this);
  }

  public boolean isLoading() {
    return OgreJNI.SkeletonInstancePtr_isLoading(swigCPtr, this);
  }

  public Resource.LoadingState getLoadingState() {
    return Resource.LoadingState.swigToEnum(OgreJNI.SkeletonInstancePtr_getLoadingState(swigCPtr, this));
  }

  public boolean isBackgroundLoaded() {
    return OgreJNI.SkeletonInstancePtr_isBackgroundLoaded(swigCPtr, this);
  }

  public void setBackgroundLoaded(boolean bl) {
    OgreJNI.SkeletonInstancePtr_setBackgroundLoaded(swigCPtr, this, bl);
  }

  public void escalateLoading() {
    OgreJNI.SkeletonInstancePtr_escalateLoading(swigCPtr, this);
  }

  public void addListener(Resource.Listener lis) {
    OgreJNI.SkeletonInstancePtr_addListener(swigCPtr, this, Resource.Listener.getCPtr(lis), lis);
  }

  public void removeListener(Resource.Listener lis) {
    OgreJNI.SkeletonInstancePtr_removeListener(swigCPtr, this, Resource.Listener.getCPtr(lis), lis);
  }

  public void changeGroupOwnership(String newGroup) {
    OgreJNI.SkeletonInstancePtr_changeGroupOwnership(swigCPtr, this, newGroup);
  }

  public ResourceManager getCreator() {
    long cPtr = OgreJNI.SkeletonInstancePtr_getCreator(swigCPtr, this);
    return (cPtr == 0) ? null : new ResourceManager(cPtr, false);
  }

  public String getOrigin() {
    return OgreJNI.SkeletonInstancePtr_getOrigin(swigCPtr, this);
  }

  public void _notifyOrigin(String origin) {
    OgreJNI.SkeletonInstancePtr__notifyOrigin(swigCPtr, this, origin);
  }

  public long getStateCount() {
    return OgreJNI.SkeletonInstancePtr_getStateCount(swigCPtr, this);
  }

  public void _dirtyState() {
    OgreJNI.SkeletonInstancePtr__dirtyState(swigCPtr, this);
  }

  public void _fireLoadingComplete(boolean wasBackgroundLoaded) {
    OgreJNI.SkeletonInstancePtr__fireLoadingComplete(swigCPtr, this, wasBackgroundLoaded);
  }

  public void _firePreparingComplete(boolean wasBackgroundLoaded) {
    OgreJNI.SkeletonInstancePtr__firePreparingComplete(swigCPtr, this, wasBackgroundLoaded);
  }

  public void _fireUnloadingComplete() {
    OgreJNI.SkeletonInstancePtr__fireUnloadingComplete(swigCPtr, this);
  }

  public ParamDictionary getParamDictionary() {
    long cPtr = OgreJNI.SkeletonInstancePtr_getParamDictionary__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new ParamDictionary(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_Ogre__ParameterDef_t getParameters() {
    return new SWIGTYPE_p_std__vectorT_Ogre__ParameterDef_t(OgreJNI.SkeletonInstancePtr_getParameters(swigCPtr, this), false);
  }

  public boolean setParameter(String name, String value) {
    return OgreJNI.SkeletonInstancePtr_setParameter(swigCPtr, this, name, value);
  }

  public void setParameterList(NameValuePairList paramList) {
    OgreJNI.SkeletonInstancePtr_setParameterList(swigCPtr, this, NameValuePairList.getCPtr(paramList), paramList);
  }

  public String getParameter(String name) {
    return OgreJNI.SkeletonInstancePtr_getParameter(swigCPtr, this, name);
  }

  public void copyParametersTo(StringInterface dest) {
    OgreJNI.SkeletonInstancePtr_copyParametersTo(swigCPtr, this, StringInterface.getCPtr(dest), dest);
  }

  public void cleanupDictionary() {
    OgreJNI.SkeletonInstancePtr_cleanupDictionary(swigCPtr, this);
  }

}
