/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class Skeleton extends Resource {
  private transient long swigCPtr;

  protected Skeleton(long cPtr, boolean cMemoryOwn) {
    super(OgreJNI.Skeleton_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Skeleton obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_Skeleton(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Skeleton(ResourceManager creator, String name, long handle, String group, boolean isManual, ManualResourceLoader loader) {
    this(OgreJNI.new_Skeleton__SWIG_1(ResourceManager.getCPtr(creator), creator, name, handle, group, isManual, ManualResourceLoader.getCPtr(loader), loader), true);
  }

  public Skeleton(ResourceManager creator, String name, long handle, String group, boolean isManual) {
    this(OgreJNI.new_Skeleton__SWIG_2(ResourceManager.getCPtr(creator), creator, name, handle, group, isManual), true);
  }

  public Skeleton(ResourceManager creator, String name, long handle, String group) {
    this(OgreJNI.new_Skeleton__SWIG_3(ResourceManager.getCPtr(creator), creator, name, handle, group), true);
  }

  public Bone createBone() {
    long cPtr = OgreJNI.Skeleton_createBone__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public Bone createBone(int handle) {
    long cPtr = OgreJNI.Skeleton_createBone__SWIG_1(swigCPtr, this, handle);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public Bone createBone(String name) {
    long cPtr = OgreJNI.Skeleton_createBone__SWIG_2(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public Bone createBone(String name, int handle) {
    long cPtr = OgreJNI.Skeleton_createBone__SWIG_3(swigCPtr, this, name, handle);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public int getNumBones() {
    return OgreJNI.Skeleton_getNumBones(swigCPtr, this);
  }

  public BoneList getRootBones() {
    return new BoneList(OgreJNI.Skeleton_getRootBones(swigCPtr, this), false);
  }

  public BoneList getBones() {
    return new BoneList(OgreJNI.Skeleton_getBones(swigCPtr, this), false);
  }

  public Bone getBone(int handle) {
    long cPtr = OgreJNI.Skeleton_getBone__SWIG_0(swigCPtr, this, handle);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public Bone getBone(String name) {
    long cPtr = OgreJNI.Skeleton_getBone__SWIG_1(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Bone(cPtr, false);
  }

  public boolean hasBone(String name) {
    return OgreJNI.Skeleton_hasBone(swigCPtr, this, name);
  }

  public void setBindingPose() {
    OgreJNI.Skeleton_setBindingPose(swigCPtr, this);
  }

  public void reset(boolean resetManualBones) {
    OgreJNI.Skeleton_reset__SWIG_0(swigCPtr, this, resetManualBones);
  }

  public void reset() {
    OgreJNI.Skeleton_reset__SWIG_1(swigCPtr, this);
  }

  public Animation createAnimation(String name, float length) {
    long cPtr = OgreJNI.Skeleton_createAnimation(swigCPtr, this, name, length);
    return (cPtr == 0) ? null : new Animation(cPtr, false);
  }

  public Animation getAnimation(String name, SWIGTYPE_p_p_Ogre__LinkedSkeletonAnimationSource linker) {
    long cPtr = OgreJNI.Skeleton_getAnimation__SWIG_0(swigCPtr, this, name, SWIGTYPE_p_p_Ogre__LinkedSkeletonAnimationSource.getCPtr(linker));
    return (cPtr == 0) ? null : new Animation(cPtr, false);
  }

  public Animation getAnimation(String name) {
    long cPtr = OgreJNI.Skeleton_getAnimation__SWIG_1(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Animation(cPtr, false);
  }

  public Animation _getAnimationImpl(String name, SWIGTYPE_p_p_Ogre__LinkedSkeletonAnimationSource linker) {
    long cPtr = OgreJNI.Skeleton__getAnimationImpl__SWIG_0(swigCPtr, this, name, SWIGTYPE_p_p_Ogre__LinkedSkeletonAnimationSource.getCPtr(linker));
    return (cPtr == 0) ? null : new Animation(cPtr, false);
  }

  public Animation _getAnimationImpl(String name) {
    long cPtr = OgreJNI.Skeleton__getAnimationImpl__SWIG_1(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Animation(cPtr, false);
  }

  public boolean hasAnimation(String name) {
    return OgreJNI.Skeleton_hasAnimation(swigCPtr, this, name);
  }

  public void removeAnimation(String name) {
    OgreJNI.Skeleton_removeAnimation(swigCPtr, this, name);
  }

  public void setAnimationState(AnimationStateSet animSet) {
    OgreJNI.Skeleton_setAnimationState(swigCPtr, this, AnimationStateSet.getCPtr(animSet), animSet);
  }

  public void _initAnimationState(AnimationStateSet animSet) {
    OgreJNI.Skeleton__initAnimationState(swigCPtr, this, AnimationStateSet.getCPtr(animSet), animSet);
  }

  public void _refreshAnimationState(AnimationStateSet animSet) {
    OgreJNI.Skeleton__refreshAnimationState(swigCPtr, this, AnimationStateSet.getCPtr(animSet), animSet);
  }

  public void _getBoneMatrices(Affine3 pMatrices) {
    OgreJNI.Skeleton__getBoneMatrices(swigCPtr, this, Affine3.getCPtr(pMatrices), pMatrices);
  }

  public int getNumAnimations() {
    return OgreJNI.Skeleton_getNumAnimations(swigCPtr, this);
  }

  public Animation getAnimation(int index) {
    long cPtr = OgreJNI.Skeleton_getAnimation__SWIG_2(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Animation(cPtr, false);
  }

  public SkeletonAnimationBlendMode getBlendMode() {
    return SkeletonAnimationBlendMode.swigToEnum(OgreJNI.Skeleton_getBlendMode(swigCPtr, this));
  }

  public void setBlendMode(SkeletonAnimationBlendMode state) {
    OgreJNI.Skeleton_setBlendMode(swigCPtr, this, state.swigValue());
  }

  public void _updateTransforms() {
    OgreJNI.Skeleton__updateTransforms(swigCPtr, this);
  }

  public void optimiseAllAnimations(boolean preservingIdentityNodeTracks) {
    OgreJNI.Skeleton_optimiseAllAnimations__SWIG_0(swigCPtr, this, preservingIdentityNodeTracks);
  }

  public void optimiseAllAnimations() {
    OgreJNI.Skeleton_optimiseAllAnimations__SWIG_1(swigCPtr, this);
  }

  public void addLinkedSkeletonAnimationSource(String skelName, float scale) {
    OgreJNI.Skeleton_addLinkedSkeletonAnimationSource__SWIG_0(swigCPtr, this, skelName, scale);
  }

  public void addLinkedSkeletonAnimationSource(String skelName) {
    OgreJNI.Skeleton_addLinkedSkeletonAnimationSource__SWIG_1(swigCPtr, this, skelName);
  }

  public void removeAllLinkedSkeletonAnimationSources() {
    OgreJNI.Skeleton_removeAllLinkedSkeletonAnimationSources(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_Ogre__LinkedSkeletonAnimationSource_t getLinkedSkeletonAnimationSources() {
    return new SWIGTYPE_p_std__vectorT_Ogre__LinkedSkeletonAnimationSource_t(OgreJNI.Skeleton_getLinkedSkeletonAnimationSources(swigCPtr, this), false);
  }

  public void _notifyManualBonesDirty() {
    OgreJNI.Skeleton__notifyManualBonesDirty(swigCPtr, this);
  }

  public void _notifyManualBoneStateChange(Bone bone) {
    OgreJNI.Skeleton__notifyManualBoneStateChange(swigCPtr, this, Bone.getCPtr(bone), bone);
  }

  public boolean getManualBonesDirty() {
    return OgreJNI.Skeleton_getManualBonesDirty(swigCPtr, this);
  }

  public boolean hasManualBones() {
    return OgreJNI.Skeleton_hasManualBones(swigCPtr, this);
  }

  public void _mergeSkeletonAnimations(Skeleton source, SWIGTYPE_p_std__vectorT_unsigned_short_t boneHandleMap, StringVector animations) {
    OgreJNI.Skeleton__mergeSkeletonAnimations__SWIG_0(swigCPtr, this, Skeleton.getCPtr(source), source, SWIGTYPE_p_std__vectorT_unsigned_short_t.getCPtr(boneHandleMap), StringVector.getCPtr(animations), animations);
  }

  public void _mergeSkeletonAnimations(Skeleton source, SWIGTYPE_p_std__vectorT_unsigned_short_t boneHandleMap) {
    OgreJNI.Skeleton__mergeSkeletonAnimations__SWIG_1(swigCPtr, this, Skeleton.getCPtr(source), source, SWIGTYPE_p_std__vectorT_unsigned_short_t.getCPtr(boneHandleMap));
  }

  public void _buildMapBoneByHandle(Skeleton source, SWIGTYPE_p_std__vectorT_unsigned_short_t boneHandleMap) {
    OgreJNI.Skeleton__buildMapBoneByHandle(swigCPtr, this, Skeleton.getCPtr(source), source, SWIGTYPE_p_std__vectorT_unsigned_short_t.getCPtr(boneHandleMap));
  }

  public void _buildMapBoneByName(Skeleton source, SWIGTYPE_p_std__vectorT_unsigned_short_t boneHandleMap) {
    OgreJNI.Skeleton__buildMapBoneByName(swigCPtr, this, Skeleton.getCPtr(source), source, SWIGTYPE_p_std__vectorT_unsigned_short_t.getCPtr(boneHandleMap));
  }

}
