/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum StencilOperation {
  SOP_KEEP,
  SOP_ZERO,
  SOP_REPLACE,
  SOP_INCREMENT,
  SOP_DECREMENT,
  SOP_INCREMENT_WRAP,
  SOP_DECREMENT_WRAP,
  SOP_INVERT;

  public final int swigValue() {
    return swigValue;
  }

  public static StencilOperation swigToEnum(int swigValue) {
    StencilOperation[] swigValues = StencilOperation.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (StencilOperation swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + StencilOperation.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private StencilOperation() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private StencilOperation(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private StencilOperation(StencilOperation swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

