/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class SubRenderState {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SubRenderState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubRenderState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTShaderJNI.delete_SubRenderState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getExecutionOrder() {
    return RTShaderJNI.SubRenderState_getExecutionOrder(swigCPtr, this);
  }

  public void copyFrom(SubRenderState rhs) {
    RTShaderJNI.SubRenderState_copyFrom(swigCPtr, this, SubRenderState.getCPtr(rhs), rhs);
  }

  public boolean createCpuSubPrograms(SWIGTYPE_p_Ogre__RTShader__ProgramSet programSet) {
    return RTShaderJNI.SubRenderState_createCpuSubPrograms(swigCPtr, this, SWIGTYPE_p_Ogre__RTShader__ProgramSet.getCPtr(programSet));
  }

  public void updateGpuProgramsParams(Renderable rend, Pass pass, SWIGTYPE_p_Ogre__AutoParamDataSource source, SWIGTYPE_p_Ogre__HashedVectorT_Ogre__Light_p_t pLightList) {
    RTShaderJNI.SubRenderState_updateGpuProgramsParams(swigCPtr, this, Renderable.getCPtr(rend), rend, Pass.getCPtr(pass), pass, SWIGTYPE_p_Ogre__AutoParamDataSource.getCPtr(source), SWIGTYPE_p_Ogre__HashedVectorT_Ogre__Light_p_t.getCPtr(pLightList));
  }

  public boolean preAddToRenderState(RenderState renderState, Pass srcPass, Pass dstPass) {
    return RTShaderJNI.SubRenderState_preAddToRenderState(swigCPtr, this, RenderState.getCPtr(renderState), renderState, Pass.getCPtr(srcPass), srcPass, Pass.getCPtr(dstPass), dstPass);
  }

  public SWIGTYPE_p_Ogre__SharedPtrT_Ogre__RTShader__SubRenderStateAccessor_t getAccessor() {
    return new SWIGTYPE_p_Ogre__SharedPtrT_Ogre__RTShader__SubRenderStateAccessor_t(RTShaderJNI.SubRenderState_getAccessor__SWIG_0(swigCPtr, this), true);
  }

}
