/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum TexCoordCalcMethod {
  TEXCALC_NONE,
  TEXCALC_ENVIRONMENT_MAP,
  TEXCALC_ENVIRONMENT_MAP_PLANAR,
  TEXCALC_ENVIRONMENT_MAP_REFLECTION,
  TEXCALC_ENVIRONMENT_MAP_NORMAL,
  TEXCALC_PROJECTIVE_TEXTURE;

  public final int swigValue() {
    return swigValue;
  }

  public static TexCoordCalcMethod swigToEnum(int swigValue) {
    TexCoordCalcMethod[] swigValues = TexCoordCalcMethod.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (TexCoordCalcMethod swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + TexCoordCalcMethod.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private TexCoordCalcMethod() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private TexCoordCalcMethod(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private TexCoordCalcMethod(TexCoordCalcMethod swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

