/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class TextInputEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TextInputEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TextInputEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BitesJNI.delete_TextInputEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    BitesJNI.TextInputEvent_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return BitesJNI.TextInputEvent_type_get(swigCPtr, this);
  }

  public void setChars(String value) {
    BitesJNI.TextInputEvent_chars_set(swigCPtr, this, value);
  }

  public String getChars() {
    return BitesJNI.TextInputEvent_chars_get(swigCPtr, this);
  }

  public TextInputEvent() {
    this(BitesJNI.new_TextInputEvent(), true);
  }

}
