/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum TextureAccess {
  TA_READ(OgreJNI.TA_READ_get()),
  TA_WRITE(OgreJNI.TA_WRITE_get()),
  TA_READ_WRITE(OgreJNI.TA_READ_WRITE_get());

  public final int swigValue() {
    return swigValue;
  }

  public static TextureAccess swigToEnum(int swigValue) {
    TextureAccess[] swigValues = TextureAccess.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (TextureAccess swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + TextureAccess.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private TextureAccess() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private TextureAccess(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private TextureAccess(TextureAccess swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

