/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum TextureAddressingMode {
  TAM_WRAP,
  TAM_MIRROR,
  TAM_CLAMP,
  TAM_BORDER,
  TAM_UNKNOWN(OgreJNI.TAM_UNKNOWN_get());

  public final int swigValue() {
    return swigValue;
  }

  public static TextureAddressingMode swigToEnum(int swigValue) {
    TextureAddressingMode[] swigValues = TextureAddressingMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (TextureAddressingMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + TextureAddressingMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private TextureAddressingMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private TextureAddressingMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private TextureAddressingMode(TextureAddressingMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

