/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class TextAreaOverlayElementPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TextAreaOverlayElementPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TextAreaOverlayElementPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreOverlayJNI.delete_TextAreaOverlayElementPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TextAreaOverlayElementPtr(SWIGTYPE_p_std__nullptr_t arg0) {
    this(OgreOverlayJNI.new_TextAreaOverlayElementPtr__SWIG_0(SWIGTYPE_p_std__nullptr_t.getCPtr(arg0)), true);
  }

  public TextAreaOverlayElementPtr() {
    this(OgreOverlayJNI.new_TextAreaOverlayElementPtr__SWIG_1(), true);
  }

  public TextAreaOverlayElementPtr(TextAreaOverlayElementPtr r) {
    this(OgreOverlayJNI.new_TextAreaOverlayElementPtr__SWIG_2(TextAreaOverlayElementPtr.getCPtr(r), r), true);
  }

  public TextAreaOverlayElement __deref__() {
    long cPtr = OgreOverlayJNI.TextAreaOverlayElementPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new TextAreaOverlayElement(cPtr, false);
  }

  public void initialise() {
    OgreOverlayJNI.TextAreaOverlayElementPtr_initialise(swigCPtr, this);
  }

  public void _releaseManualHardwareResources() {
    OgreOverlayJNI.TextAreaOverlayElementPtr__releaseManualHardwareResources(swigCPtr, this);
  }

  public void _restoreManualHardwareResources() {
    OgreOverlayJNI.TextAreaOverlayElementPtr__restoreManualHardwareResources(swigCPtr, this);
  }

  public void setCaption(SWIGTYPE_p_UTFString text) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setCaption(swigCPtr, this, SWIGTYPE_p_UTFString.getCPtr(text));
  }

  public void setCharHeight(float height) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setCharHeight(swigCPtr, this, height);
  }

  public float getCharHeight() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getCharHeight(swigCPtr, this);
  }

  public void setSpaceWidth(float width) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setSpaceWidth(swigCPtr, this, width);
  }

  public float getSpaceWidth() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getSpaceWidth(swigCPtr, this);
  }

  public void setFontName(String font, String group) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setFontName__SWIG_0(swigCPtr, this, font, group);
  }

  public void setFontName(String font) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setFontName__SWIG_1(swigCPtr, this, font);
  }

  public FontPtr getFont() {
    return new FontPtr(OgreOverlayJNI.TextAreaOverlayElementPtr_getFont(swigCPtr, this), false);
  }

  public String getTypeName() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getTypeName(swigCPtr, this);
  }

  public MaterialPtr getMaterial() {
    return new MaterialPtr(OgreOverlayJNI.TextAreaOverlayElementPtr_getMaterial(swigCPtr, this), false);
  }

  public void getRenderOperation(RenderOperation op) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_getRenderOperation(swigCPtr, this, RenderOperation.getCPtr(op), op);
  }

  public void setColour(ColourValue col) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setColour(swigCPtr, this, ColourValue.getCPtr(col), col);
  }

  public ColourValue getColour() {
    return new ColourValue(OgreOverlayJNI.TextAreaOverlayElementPtr_getColour(swigCPtr, this), false);
  }

  public void setColourBottom(ColourValue col) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setColourBottom(swigCPtr, this, ColourValue.getCPtr(col), col);
  }

  public ColourValue getColourBottom() {
    return new ColourValue(OgreOverlayJNI.TextAreaOverlayElementPtr_getColourBottom(swigCPtr, this), false);
  }

  public void setColourTop(ColourValue col) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setColourTop(swigCPtr, this, ColourValue.getCPtr(col), col);
  }

  public ColourValue getColourTop() {
    return new ColourValue(OgreOverlayJNI.TextAreaOverlayElementPtr_getColourTop(swigCPtr, this), false);
  }

  public void setAlignment(TextAreaOverlayElement.Alignment a) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setAlignment(swigCPtr, this, a.swigValue());
  }

  public TextAreaOverlayElement.Alignment getAlignment() {
    return TextAreaOverlayElement.Alignment.swigToEnum(OgreOverlayJNI.TextAreaOverlayElementPtr_getAlignment(swigCPtr, this));
  }

  public void setMetricsMode(GuiMetricsMode gmm) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setMetricsMode(swigCPtr, this, gmm.swigValue());
  }

  public void _update() {
    OgreOverlayJNI.TextAreaOverlayElementPtr__update(swigCPtr, this);
  }

  public String getDEFAULT_RESOURCE_GROUP() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_DEFAULT_RESOURCE_GROUP_get(swigCPtr, this);
  }

  public String getName() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getName(swigCPtr, this);
  }

  public void show() {
    OgreOverlayJNI.TextAreaOverlayElementPtr_show(swigCPtr, this);
  }

  public void hide() {
    OgreOverlayJNI.TextAreaOverlayElementPtr_hide(swigCPtr, this);
  }

  public boolean isVisible() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_isVisible(swigCPtr, this);
  }

  public boolean isEnabled() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_isEnabled(swigCPtr, this);
  }

  public void setEnabled(boolean b) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setEnabled(swigCPtr, this, b);
  }

  public void setDimensions(float width, float height) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setDimensions(swigCPtr, this, width, height);
  }

  public void setPosition(float left, float top) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setPosition(swigCPtr, this, left, top);
  }

  public void setWidth(float width) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setWidth(swigCPtr, this, width);
  }

  public float getWidth() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getWidth(swigCPtr, this);
  }

  public void setHeight(float height) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setHeight(swigCPtr, this, height);
  }

  public float getHeight() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getHeight(swigCPtr, this);
  }

  public void setLeft(float left) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setLeft(swigCPtr, this, left);
  }

  public float getLeft() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getLeft(swigCPtr, this);
  }

  public void setTop(float Top) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setTop(swigCPtr, this, Top);
  }

  public float getTop() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getTop(swigCPtr, this);
  }

  public float _getLeft() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr__getLeft(swigCPtr, this);
  }

  public float _getTop() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr__getTop(swigCPtr, this);
  }

  public float _getWidth() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr__getWidth(swigCPtr, this);
  }

  public float _getHeight() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr__getHeight(swigCPtr, this);
  }

  public void _setLeft(float left) {
    OgreOverlayJNI.TextAreaOverlayElementPtr__setLeft(swigCPtr, this, left);
  }

  public void _setTop(float top) {
    OgreOverlayJNI.TextAreaOverlayElementPtr__setTop(swigCPtr, this, top);
  }

  public void _setWidth(float width) {
    OgreOverlayJNI.TextAreaOverlayElementPtr__setWidth(swigCPtr, this, width);
  }

  public void _setHeight(float height) {
    OgreOverlayJNI.TextAreaOverlayElementPtr__setHeight(swigCPtr, this, height);
  }

  public void _setPosition(float left, float top) {
    OgreOverlayJNI.TextAreaOverlayElementPtr__setPosition(swigCPtr, this, left, top);
  }

  public void _setDimensions(float width, float height) {
    OgreOverlayJNI.TextAreaOverlayElementPtr__setDimensions(swigCPtr, this, width, height);
  }

  public String getMaterialName() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getMaterialName(swigCPtr, this);
  }

  public void setMaterial(MaterialPtr mat) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setMaterial(swigCPtr, this, MaterialPtr.getCPtr(mat), mat);
  }

  public void setMaterialName(String matName, String group) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setMaterialName__SWIG_0(swigCPtr, this, matName, group);
  }

  public void setMaterialName(String matName) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setMaterialName__SWIG_1(swigCPtr, this, matName);
  }

  public void getWorldTransforms(Matrix4 xform) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_getWorldTransforms(swigCPtr, this, Matrix4.getCPtr(xform), xform);
  }

  public void _positionsOutOfDate() {
    OgreOverlayJNI.TextAreaOverlayElementPtr__positionsOutOfDate(swigCPtr, this);
  }

  public void _updateFromParent() {
    OgreOverlayJNI.TextAreaOverlayElementPtr__updateFromParent(swigCPtr, this);
  }

  public void _notifyParent(OverlayContainer parent, Overlay overlay) {
    OgreOverlayJNI.TextAreaOverlayElementPtr__notifyParent(swigCPtr, this, OverlayContainer.getCPtr(parent), parent, Overlay.getCPtr(overlay), overlay);
  }

  public float _getDerivedLeft() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr__getDerivedLeft(swigCPtr, this);
  }

  public float _getDerivedTop() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr__getDerivedTop(swigCPtr, this);
  }

  public float _getRelativeWidth() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr__getRelativeWidth(swigCPtr, this);
  }

  public float _getRelativeHeight() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr__getRelativeHeight(swigCPtr, this);
  }

  public void _getClippingRegion(FloatRect clippingRegion) {
    OgreOverlayJNI.TextAreaOverlayElementPtr__getClippingRegion(swigCPtr, this, FloatRect.getCPtr(clippingRegion), clippingRegion);
  }

  public int _notifyZOrder(int newZOrder) {
    return OgreOverlayJNI.TextAreaOverlayElementPtr__notifyZOrder(swigCPtr, this, newZOrder);
  }

  public void _notifyWorldTransforms(Matrix4 xform) {
    OgreOverlayJNI.TextAreaOverlayElementPtr__notifyWorldTransforms(swigCPtr, this, Matrix4.getCPtr(xform), xform);
  }

  public void _notifyViewport() {
    OgreOverlayJNI.TextAreaOverlayElementPtr__notifyViewport(swigCPtr, this);
  }

  public void _updateRenderQueue(RenderQueue queue) {
    OgreOverlayJNI.TextAreaOverlayElementPtr__updateRenderQueue(swigCPtr, this, RenderQueue.getCPtr(queue), queue);
  }

  public void visitRenderables(Renderable.Visitor visitor, boolean debugRenderables) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_visitRenderables__SWIG_0(swigCPtr, this, Renderable.Visitor.getCPtr(visitor), visitor, debugRenderables);
  }

  public void visitRenderables(Renderable.Visitor visitor) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_visitRenderables__SWIG_1(swigCPtr, this, Renderable.Visitor.getCPtr(visitor), visitor);
  }

  public SWIGTYPE_p_UTFString getCaption() {
    return new SWIGTYPE_p_UTFString(OgreOverlayJNI.TextAreaOverlayElementPtr_getCaption(swigCPtr, this), false);
  }

  public GuiMetricsMode getMetricsMode() {
    return GuiMetricsMode.swigToEnum(OgreOverlayJNI.TextAreaOverlayElementPtr_getMetricsMode(swigCPtr, this));
  }

  public void setHorizontalAlignment(GuiHorizontalAlignment gha) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setHorizontalAlignment(swigCPtr, this, gha.swigValue());
  }

  public GuiHorizontalAlignment getHorizontalAlignment() {
    return GuiHorizontalAlignment.swigToEnum(OgreOverlayJNI.TextAreaOverlayElementPtr_getHorizontalAlignment(swigCPtr, this));
  }

  public void setVerticalAlignment(GuiVerticalAlignment gva) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setVerticalAlignment(swigCPtr, this, gva.swigValue());
  }

  public GuiVerticalAlignment getVerticalAlignment() {
    return GuiVerticalAlignment.swigToEnum(OgreOverlayJNI.TextAreaOverlayElementPtr_getVerticalAlignment(swigCPtr, this));
  }

  public boolean contains(float x, float y) {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_contains(swigCPtr, this, x, y);
  }

  public OverlayElement findElementAt(float x, float y) {
    long cPtr = OgreOverlayJNI.TextAreaOverlayElementPtr_findElementAt(swigCPtr, this, x, y);
    return (cPtr == 0) ? null : new OverlayElement(cPtr, false);
  }

  public boolean isContainer() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_isContainer(swigCPtr, this);
  }

  public boolean isKeyEnabled() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_isKeyEnabled(swigCPtr, this);
  }

  public boolean isCloneable() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_isCloneable(swigCPtr, this);
  }

  public void setCloneable(boolean c) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setCloneable(swigCPtr, this, c);
  }

  public OverlayContainer getParent() {
    long cPtr = OgreOverlayJNI.TextAreaOverlayElementPtr_getParent(swigCPtr, this);
    return (cPtr == 0) ? null : new OverlayContainer(cPtr, false);
  }

  public void _setParent(OverlayContainer parent) {
    OgreOverlayJNI.TextAreaOverlayElementPtr__setParent(swigCPtr, this, OverlayContainer.getCPtr(parent), parent);
  }

  public int getZOrder() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getZOrder(swigCPtr, this);
  }

  public float getSquaredViewDepth(Camera cam) {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getSquaredViewDepth(swigCPtr, this, Camera.getCPtr(cam), cam);
  }

  public SWIGTYPE_p_Ogre__HashedVectorT_Ogre__Light_p_t getLights() {
    return new SWIGTYPE_p_Ogre__HashedVectorT_Ogre__Light_p_t(OgreOverlayJNI.TextAreaOverlayElementPtr_getLights(swigCPtr, this), false);
  }

  public void copyFromTemplate(OverlayElement templateOverlay) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_copyFromTemplate(swigCPtr, this, OverlayElement.getCPtr(templateOverlay), templateOverlay);
  }

  public OverlayElement clone(String instanceName) {
    long cPtr = OgreOverlayJNI.TextAreaOverlayElementPtr_clone(swigCPtr, this, instanceName);
    return (cPtr == 0) ? null : new OverlayElement(cPtr, false);
  }

  public OverlayElement getSourceTemplate() {
    long cPtr = OgreOverlayJNI.TextAreaOverlayElementPtr_getSourceTemplate(swigCPtr, this);
    return (cPtr == 0) ? null : new OverlayElement(cPtr, false);
  }

  public ParamDictionary getParamDictionary() {
    long cPtr = OgreOverlayJNI.TextAreaOverlayElementPtr_getParamDictionary__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new ParamDictionary(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_Ogre__ParameterDef_t getParameters() {
    return new SWIGTYPE_p_std__vectorT_Ogre__ParameterDef_t(OgreOverlayJNI.TextAreaOverlayElementPtr_getParameters(swigCPtr, this), false);
  }

  public boolean setParameter(String name, String value) {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_setParameter(swigCPtr, this, name, value);
  }

  public void setParameterList(NameValuePairList paramList) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setParameterList(swigCPtr, this, NameValuePairList.getCPtr(paramList), paramList);
  }

  public String getParameter(String name) {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getParameter(swigCPtr, this, name);
  }

  public void copyParametersTo(StringInterface dest) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_copyParametersTo(swigCPtr, this, StringInterface.getCPtr(dest), dest);
  }

  public void cleanupDictionary() {
    OgreOverlayJNI.TextAreaOverlayElementPtr_cleanupDictionary(swigCPtr, this);
  }

  public Technique getTechnique() {
    long cPtr = OgreOverlayJNI.TextAreaOverlayElementPtr_getTechnique(swigCPtr, this);
    return (cPtr == 0) ? null : new Technique(cPtr, false);
  }

  public boolean preRender(SceneManager sm, RenderSystem rsys) {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_preRender(swigCPtr, this, SceneManager.getCPtr(sm), sm, RenderSystem.getCPtr(rsys), rsys);
  }

  public void postRender(SceneManager sm, RenderSystem rsys) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_postRender(swigCPtr, this, SceneManager.getCPtr(sm), sm, RenderSystem.getCPtr(rsys), rsys);
  }

  public int getNumWorldTransforms() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getNumWorldTransforms(swigCPtr, this);
  }

  public void setUseIdentityProjection(boolean useIdentityProjection) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setUseIdentityProjection(swigCPtr, this, useIdentityProjection);
  }

  public boolean getUseIdentityProjection() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getUseIdentityProjection(swigCPtr, this);
  }

  public void setUseIdentityView(boolean useIdentityView) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setUseIdentityView(swigCPtr, this, useIdentityView);
  }

  public boolean getUseIdentityView() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getUseIdentityView(swigCPtr, this);
  }

  public boolean getCastsShadows() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getCastsShadows(swigCPtr, this);
  }

  public void setCustomParameter(long index, Vector4 value) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setCustomParameter(swigCPtr, this, index, Vector4.getCPtr(value), value);
  }

  public void removeCustomParameter(long index) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_removeCustomParameter(swigCPtr, this, index);
  }

  public boolean hasCustomParameter(long index) {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_hasCustomParameter(swigCPtr, this, index);
  }

  public Vector4 getCustomParameter(long index) {
    return new Vector4(OgreOverlayJNI.TextAreaOverlayElementPtr_getCustomParameter(swigCPtr, this, index), false);
  }

  public void _updateCustomGpuParameter(GpuProgramParameters.AutoConstantEntry constantEntry, GpuProgramParameters params) {
    OgreOverlayJNI.TextAreaOverlayElementPtr__updateCustomGpuParameter(swigCPtr, this, GpuProgramParameters.AutoConstantEntry.getCPtr(constantEntry), constantEntry, GpuProgramParameters.getCPtr(params), params);
  }

  public void setPolygonModeOverrideable(boolean override) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setPolygonModeOverrideable(swigCPtr, this, override);
  }

  public boolean getPolygonModeOverrideable() {
    return OgreOverlayJNI.TextAreaOverlayElementPtr_getPolygonModeOverrideable(swigCPtr, this);
  }

  public UserObjectBindings getUserObjectBindings() {
    return new UserObjectBindings(OgreOverlayJNI.TextAreaOverlayElementPtr_getUserObjectBindings__SWIG_0(swigCPtr, this), false);
  }

  public SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Renderable__RenderSystemData_t getRenderSystemData() {
    return new SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Renderable__RenderSystemData_t(OgreOverlayJNI.TextAreaOverlayElementPtr_getRenderSystemData(swigCPtr, this), false);
  }

  public void setRenderSystemData(SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Renderable__RenderSystemData_t val) {
    OgreOverlayJNI.TextAreaOverlayElementPtr_setRenderSystemData(swigCPtr, this, SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Renderable__RenderSystemData_t.getCPtr(val));
  }

}
