/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class TouchFingerEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TouchFingerEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TouchFingerEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BitesJNI.delete_TouchFingerEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    BitesJNI.TouchFingerEvent_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return BitesJNI.TouchFingerEvent_type_get(swigCPtr, this);
  }

  public void setFingerId(int value) {
    BitesJNI.TouchFingerEvent_fingerId_set(swigCPtr, this, value);
  }

  public int getFingerId() {
    return BitesJNI.TouchFingerEvent_fingerId_get(swigCPtr, this);
  }

  public void setX(float value) {
    BitesJNI.TouchFingerEvent_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return BitesJNI.TouchFingerEvent_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    BitesJNI.TouchFingerEvent_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return BitesJNI.TouchFingerEvent_y_get(swigCPtr, this);
  }

  public void setDx(float value) {
    BitesJNI.TouchFingerEvent_dx_set(swigCPtr, this, value);
  }

  public float getDx() {
    return BitesJNI.TouchFingerEvent_dx_get(swigCPtr, this);
  }

  public void setDy(float value) {
    BitesJNI.TouchFingerEvent_dy_set(swigCPtr, this, value);
  }

  public float getDy() {
    return BitesJNI.TouchFingerEvent_dy_get(swigCPtr, this);
  }

  public TouchFingerEvent() {
    this(BitesJNI.new_TouchFingerEvent(), true);
  }

}
