/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class Vector3i extends VectorBase3i {
  private transient long swigCPtr;

  protected Vector3i(long cPtr, boolean cMemoryOwn) {
    super(OgreJNI.Vector3i_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vector3i obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_Vector3i(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SWIGTYPE_p_int ptr() {
    long cPtr = OgreJNI.Vector3i_ptr_SWIG_0_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public Vector3i() {
    this(OgreJNI.new_Vector3i__SWIG_0(), true);
  }

  public Vector3i(int _x, int _y) {
    this(OgreJNI.new_Vector3i__SWIG_1(_x, _y), true);
  }

  public Vector3i(int _x, int _y, int _z) {
    this(OgreJNI.new_Vector3i__SWIG_2(_x, _y, _z), true);
  }

  public Vector3i(int s) {
    this(OgreJNI.new_Vector3i__SWIG_3(s), true);
  }

  public SWIGTYPE_p_Ogre__VectorT_2_int_t xy() {
    return new SWIGTYPE_p_Ogre__VectorT_2_int_t(OgreJNI.Vector3i_xy(swigCPtr, this), true);
  }

  public int __getitem__(long i) {
    return OgreJNI.Vector3i___getitem____SWIG_0(swigCPtr, this, i);
  }

  public boolean positionEquals(Vector3i rhs, float tolerance) {
    return OgreJNI.Vector3i_positionEquals__SWIG_0(swigCPtr, this, Vector3i.getCPtr(rhs), rhs, tolerance);
  }

  public boolean positionEquals(Vector3i rhs) {
    return OgreJNI.Vector3i_positionEquals__SWIG_1(swigCPtr, this, Vector3i.getCPtr(rhs), rhs);
  }

  public void makeFloor(Vector3i cmp) {
    OgreJNI.Vector3i_makeFloor(swigCPtr, this, Vector3i.getCPtr(cmp), cmp);
  }

  public void makeCeil(Vector3i cmp) {
    OgreJNI.Vector3i_makeCeil(swigCPtr, this, Vector3i.getCPtr(cmp), cmp);
  }

  public int dotProduct(VectorBase3i vec) {
    return OgreJNI.Vector3i_dotProduct(swigCPtr, this, VectorBase3i.getCPtr(vec), vec);
  }

  public int squaredLength() {
    return OgreJNI.Vector3i_squaredLength(swigCPtr, this);
  }

  public boolean isZeroLength() {
    return OgreJNI.Vector3i_isZeroLength(swigCPtr, this);
  }

  public float length() {
    return OgreJNI.Vector3i_length(swigCPtr, this);
  }

  public float distance(Vector3i rhs) {
    return OgreJNI.Vector3i_distance(swigCPtr, this, Vector3i.getCPtr(rhs), rhs);
  }

  public int squaredDistance(Vector3i rhs) {
    return OgreJNI.Vector3i_squaredDistance(swigCPtr, this, Vector3i.getCPtr(rhs), rhs);
  }

  public float normalise() {
    return OgreJNI.Vector3i_normalise(swigCPtr, this);
  }

  public Vector3i normalisedCopy() {
    return new Vector3i(OgreJNI.Vector3i_normalisedCopy(swigCPtr, this), true);
  }

  public boolean isNaN() {
    return OgreJNI.Vector3i_isNaN(swigCPtr, this);
  }

  public Radian angleBetween(Vector3i dest) {
    return new Radian(OgreJNI.Vector3i_angleBetween(swigCPtr, this, Vector3i.getCPtr(dest), dest), true);
  }

  public Vector3i reflect(Vector3i normal) {
    return new Vector3i(OgreJNI.Vector3i_reflect(swigCPtr, this, Vector3i.getCPtr(normal), normal), true);
  }

  public Vector3i __sub__() {
    return new Vector3i(OgreJNI.Vector3i___sub____SWIG_0(swigCPtr, this), true);
  }

  public Vector3i __add__() {
    return new Vector3i(OgreJNI.Vector3i___add____SWIG_0(swigCPtr, this), false);
  }

  public Vector3i __mul__(float s) {
    return new Vector3i(OgreJNI.Vector3i___mul____SWIG_0(swigCPtr, this, s), true);
  }

  public Vector3i __div__(float s) {
    return new Vector3i(OgreJNI.Vector3i___div____SWIG_0(swigCPtr, this, s), true);
  }

  public Vector3i __sub__(float s) {
    return new Vector3i(OgreJNI.Vector3i___sub____SWIG_1(swigCPtr, this, s), true);
  }

  public Vector3i __add__(float s) {
    return new Vector3i(OgreJNI.Vector3i___add____SWIG_1(swigCPtr, this, s), true);
  }

  public Vector3i __add__(Vector3i b) {
    return new Vector3i(OgreJNI.Vector3i___add____SWIG_2(swigCPtr, this, Vector3i.getCPtr(b), b), true);
  }

  public Vector3i __sub__(Vector3i b) {
    return new Vector3i(OgreJNI.Vector3i___sub____SWIG_2(swigCPtr, this, Vector3i.getCPtr(b), b), true);
  }

  public Vector3i __mul__(Vector3i b) {
    return new Vector3i(OgreJNI.Vector3i___mul____SWIG_1(swigCPtr, this, Vector3i.getCPtr(b), b), true);
  }

  public Vector3i __div__(Vector3i b) {
    return new Vector3i(OgreJNI.Vector3i___div____SWIG_1(swigCPtr, this, Vector3i.getCPtr(b), b), true);
  }

  public String toString() {
    return OgreJNI.Vector3i_toString(swigCPtr, this);
  }

}
