/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public class Vector4 extends VectorBase4 {
  private transient long swigCPtr;

  protected Vector4(long cPtr, boolean cMemoryOwn) {
    super(OgreJNI.Vector4_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vector4 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_Vector4(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Vector4() {
    this(OgreJNI.new_Vector4__SWIG_0(), true);
  }

  public Vector4(float _x, float _y, float _z, float _w) {
    this(OgreJNI.new_Vector4__SWIG_1(_x, _y, _z, _w), true);
  }

  public Vector4(float s) {
    this(OgreJNI.new_Vector4__SWIG_2(s), true);
  }

  public Vector3 xyz() {
    return new Vector3(OgreJNI.Vector4_xyz(swigCPtr, this), true);
  }

  public Vector2 xy() {
    return new Vector2(OgreJNI.Vector4_xy(swigCPtr, this), true);
  }

  public float __getitem__(long i) {
    return OgreJNI.Vector4___getitem____SWIG_0(swigCPtr, this, i);
  }

  public boolean positionEquals(Vector4 rhs, float tolerance) {
    return OgreJNI.Vector4_positionEquals__SWIG_0(swigCPtr, this, Vector4.getCPtr(rhs), rhs, tolerance);
  }

  public boolean positionEquals(Vector4 rhs) {
    return OgreJNI.Vector4_positionEquals__SWIG_1(swigCPtr, this, Vector4.getCPtr(rhs), rhs);
  }

  public void makeFloor(Vector4 cmp) {
    OgreJNI.Vector4_makeFloor(swigCPtr, this, Vector4.getCPtr(cmp), cmp);
  }

  public void makeCeil(Vector4 cmp) {
    OgreJNI.Vector4_makeCeil(swigCPtr, this, Vector4.getCPtr(cmp), cmp);
  }

  public float dotProduct(VectorBase4 vec) {
    return OgreJNI.Vector4_dotProduct(swigCPtr, this, VectorBase4.getCPtr(vec), vec);
  }

  public float squaredLength() {
    return OgreJNI.Vector4_squaredLength(swigCPtr, this);
  }

  public boolean isZeroLength() {
    return OgreJNI.Vector4_isZeroLength(swigCPtr, this);
  }

  public float length() {
    return OgreJNI.Vector4_length(swigCPtr, this);
  }

  public float distance(Vector4 rhs) {
    return OgreJNI.Vector4_distance(swigCPtr, this, Vector4.getCPtr(rhs), rhs);
  }

  public float squaredDistance(Vector4 rhs) {
    return OgreJNI.Vector4_squaredDistance(swigCPtr, this, Vector4.getCPtr(rhs), rhs);
  }

  public float normalise() {
    return OgreJNI.Vector4_normalise(swigCPtr, this);
  }

  public Vector4 normalisedCopy() {
    return new Vector4(OgreJNI.Vector4_normalisedCopy(swigCPtr, this), true);
  }

  public boolean isNaN() {
    return OgreJNI.Vector4_isNaN(swigCPtr, this);
  }

  public Radian angleBetween(Vector4 dest) {
    return new Radian(OgreJNI.Vector4_angleBetween(swigCPtr, this, Vector4.getCPtr(dest), dest), true);
  }

  public Vector4 reflect(Vector4 normal) {
    return new Vector4(OgreJNI.Vector4_reflect(swigCPtr, this, Vector4.getCPtr(normal), normal), true);
  }

  public Vector4 __sub__() {
    return new Vector4(OgreJNI.Vector4___sub____SWIG_0(swigCPtr, this), true);
  }

  public Vector4 __add__() {
    return new Vector4(OgreJNI.Vector4___add____SWIG_0(swigCPtr, this), false);
  }

  public Vector4 __mul__(float s) {
    return new Vector4(OgreJNI.Vector4___mul____SWIG_0(swigCPtr, this, s), true);
  }

  public Vector4 __div__(float s) {
    return new Vector4(OgreJNI.Vector4___div____SWIG_0(swigCPtr, this, s), true);
  }

  public Vector4 __sub__(float s) {
    return new Vector4(OgreJNI.Vector4___sub____SWIG_1(swigCPtr, this, s), true);
  }

  public Vector4 __add__(float s) {
    return new Vector4(OgreJNI.Vector4___add____SWIG_1(swigCPtr, this, s), true);
  }

  public Vector4 __add__(Vector4 b) {
    return new Vector4(OgreJNI.Vector4___add____SWIG_2(swigCPtr, this, Vector4.getCPtr(b), b), true);
  }

  public Vector4 __sub__(Vector4 b) {
    return new Vector4(OgreJNI.Vector4___sub____SWIG_2(swigCPtr, this, Vector4.getCPtr(b), b), true);
  }

  public Vector4 __mul__(Vector4 b) {
    return new Vector4(OgreJNI.Vector4___mul____SWIG_1(swigCPtr, this, Vector4.getCPtr(b), b), true);
  }

  public Vector4 __div__(Vector4 b) {
    return new Vector4(OgreJNI.Vector4___div____SWIG_1(swigCPtr, this, Vector4.getCPtr(b), b), true);
  }

  public String toString() {
    return OgreJNI.Vector4_toString(swigCPtr, this);
  }

}
