/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ogre;

public enum VSOutputCompactPolicy {
  VSOCP_LOW(RTShaderJNI.VSOCP_LOW_get()),
  VSOCP_MEDIUM(RTShaderJNI.VSOCP_MEDIUM_get()),
  VSOCP_HIGH(RTShaderJNI.VSOCP_HIGH_get());

  public final int swigValue() {
    return swigValue;
  }

  public static VSOutputCompactPolicy swigToEnum(int swigValue) {
    VSOutputCompactPolicy[] swigValues = VSOutputCompactPolicy.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (VSOutputCompactPolicy swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + VSOutputCompactPolicy.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private VSOutputCompactPolicy() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private VSOutputCompactPolicy(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private VSOutputCompactPolicy(VSOutputCompactPolicy swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

